//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.03 at 11:01:00 ���� KST 
//


package com.koreanair.common_adapter.altea.vo.ticket_retrievelistoftsmreply_09_1_1a;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.koreanair.common_adapter.altea.vo.ticket_retrievelistoftsmreply_09_1_1a package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.koreanair.common_adapter.altea.vo.ticket_retrievelistoftsmreply_09_1_1a
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StatusDetailsTypeI }
     * 
     */
    public StatusDetailsTypeI createStatusDetailsTypeI() {
        return new StatusDetailsTypeI();
    }

    /**
     * Create an instance of {@link ApplicationErrorDetailType }
     * 
     */
    public ApplicationErrorDetailType createApplicationErrorDetailType() {
        return new ApplicationErrorDetailType();
    }

    /**
     * Create an instance of {@link TravellerDetailsTypeI }
     * 
     */
    public TravellerDetailsTypeI createTravellerDetailsTypeI() {
        return new TravellerDetailsTypeI();
    }

    /**
     * Create an instance of {@link TicketRetrieveListOfTSMReply.DetailsOfRetrievedTSMs }
     * 
     */
    public TicketRetrieveListOfTSMReply.DetailsOfRetrievedTSMs createTicketRetrieveListOfTSMReplyDetailsOfRetrievedTSMs() {
        return new TicketRetrieveListOfTSMReply.DetailsOfRetrievedTSMs();
    }

    /**
     * Create an instance of {@link AttributeInformationTypeU }
     * 
     */
    public AttributeInformationTypeU createAttributeInformationTypeU() {
        return new AttributeInformationTypeU();
    }

    /**
     * Create an instance of {@link MonetaryInformationTypeI }
     * 
     */
    public MonetaryInformationTypeI createMonetaryInformationTypeI() {
        return new MonetaryInformationTypeI();
    }

    /**
     * Create an instance of {@link ReferencingDetailsTypeI }
     * 
     */
    public ReferencingDetailsTypeI createReferencingDetailsTypeI() {
        return new ReferencingDetailsTypeI();
    }

    /**
     * Create an instance of {@link ReferenceInformationType }
     * 
     */
    public ReferenceInformationType createReferenceInformationType() {
        return new ReferenceInformationType();
    }

    /**
     * Create an instance of {@link MonetaryInformationDetailsTypeI }
     * 
     */
    public MonetaryInformationDetailsTypeI createMonetaryInformationDetailsTypeI() {
        return new MonetaryInformationDetailsTypeI();
    }

    /**
     * Create an instance of {@link ItemReferencesAndVersionsType }
     * 
     */
    public ItemReferencesAndVersionsType createItemReferencesAndVersionsType() {
        return new ItemReferencesAndVersionsType();
    }

    /**
     * Create an instance of {@link StatusTypeI }
     * 
     */
    public StatusTypeI createStatusTypeI() {
        return new StatusTypeI();
    }

    /**
     * Create an instance of {@link TravellerInformationTypeI }
     * 
     */
    public TravellerInformationTypeI createTravellerInformationTypeI() {
        return new TravellerInformationTypeI();
    }

    /**
     * Create an instance of {@link ReferenceInformationTypeI }
     * 
     */
    public ReferenceInformationTypeI createReferenceInformationTypeI() {
        return new ReferenceInformationTypeI();
    }

    /**
     * Create an instance of {@link TicketRetrieveListOfTSMReply }
     * 
     */
    public TicketRetrieveListOfTSMReply createTicketRetrieveListOfTSMReply() {
        return new TicketRetrieveListOfTSMReply();
    }

    /**
     * Create an instance of {@link TravellerSurnameInformationTypeI }
     * 
     */
    public TravellerSurnameInformationTypeI createTravellerSurnameInformationTypeI() {
        return new TravellerSurnameInformationTypeI();
    }

    /**
     * Create an instance of {@link FreeTextInformationType }
     * 
     */
    public FreeTextInformationType createFreeTextInformationType() {
        return new FreeTextInformationType();
    }

    /**
     * Create an instance of {@link ErrorGroupType }
     * 
     */
    public ErrorGroupType createErrorGroupType() {
        return new ErrorGroupType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link FreeTextDetailsType }
     * 
     */
    public FreeTextDetailsType createFreeTextDetailsType() {
        return new FreeTextDetailsType();
    }

    /**
     * Create an instance of {@link ApplicationErrorInformationType }
     * 
     */
    public ApplicationErrorInformationType createApplicationErrorInformationType() {
        return new ApplicationErrorInformationType();
    }

}
