//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.20 at 02:05:37 PM KST 
//


package com.koreanair.common_external.pid.gps.approvalRequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for nPayInfo2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="nPayInfo2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cardAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cardCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cardName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cardQuota" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cardInterest" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cardCl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cardBin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cardPoint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="stateCD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ccPartCl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cancelNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nPayInfo2", propOrder = {
    "cardAmt",
    "cardCode",
    "cardName",
    "cardQuota",
    "cardInterest",
    "cardCl",
    "cardBin",
    "cardPoint",
    "stateCD",
    "ccPartCl",
    "cancelNum"
})
public class NPayInfo2 {

    protected String cardAmt;
    protected String cardCode;
    protected String cardName;
    protected String cardQuota;
    protected String cardInterest;
    protected String cardCl;
    protected String cardBin;
    protected String cardPoint;
    protected String stateCD;
    protected String ccPartCl;
    protected String cancelNum;

    /**
     * Gets the value of the cardAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardAmt() {
        return cardAmt;
    }

    /**
     * Sets the value of the cardAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardAmt(String value) {
        this.cardAmt = value;
    }

    /**
     * Gets the value of the cardCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardCode() {
        return cardCode;
    }

    /**
     * Sets the value of the cardCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardCode(String value) {
        this.cardCode = value;
    }

    /**
     * Gets the value of the cardName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardName() {
        return cardName;
    }

    /**
     * Sets the value of the cardName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardName(String value) {
        this.cardName = value;
    }

    /**
     * Gets the value of the cardQuota property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardQuota() {
        return cardQuota;
    }

    /**
     * Sets the value of the cardQuota property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardQuota(String value) {
        this.cardQuota = value;
    }

    /**
     * Gets the value of the cardInterest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardInterest() {
        return cardInterest;
    }

    /**
     * Sets the value of the cardInterest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardInterest(String value) {
        this.cardInterest = value;
    }

    /**
     * Gets the value of the cardCl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardCl() {
        return cardCl;
    }

    /**
     * Sets the value of the cardCl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardCl(String value) {
        this.cardCl = value;
    }

    /**
     * Gets the value of the cardBin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardBin() {
        return cardBin;
    }

    /**
     * Sets the value of the cardBin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardBin(String value) {
        this.cardBin = value;
    }

    /**
     * Gets the value of the cardPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardPoint() {
        return cardPoint;
    }

    /**
     * Sets the value of the cardPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardPoint(String value) {
        this.cardPoint = value;
    }

    /**
     * Gets the value of the stateCD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateCD() {
        return stateCD;
    }

    /**
     * Sets the value of the stateCD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateCD(String value) {
        this.stateCD = value;
    }

    /**
     * Gets the value of the ccPartCl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcPartCl() {
        return ccPartCl;
    }

    /**
     * Sets the value of the ccPartCl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcPartCl(String value) {
        this.ccPartCl = value;
    }

    /**
     * Gets the value of the cancelNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelNum() {
        return cancelNum;
    }

    /**
     * Sets the value of the cancelNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelNum(String value) {
        this.cancelNum = value;
    }

}
