//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.11 at 11:10:11 ���� KST 
//


package com.koreanair.common_adapter.altea.vo.airflightinfo_07_1_1a;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.koreanair.common_adapter.altea.vo.airflightinfo_07_1_1a package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.koreanair.common_adapter.altea.vo.airflightinfo_07_1_1a
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AirFlightInfo.GeneralFlightInfo.MarriageDetails }
     * 
     */
    public AirFlightInfo.GeneralFlightInfo.MarriageDetails createAirFlightInfoGeneralFlightInfoMarriageDetails() {
        return new AirFlightInfo.GeneralFlightInfo.MarriageDetails();
    }

    /**
     * Create an instance of {@link AirFlightInfo.GeneralFlightInfo.OffPointDetails }
     * 
     */
    public AirFlightInfo.GeneralFlightInfo.OffPointDetails createAirFlightInfoGeneralFlightInfoOffPointDetails() {
        return new AirFlightInfo.GeneralFlightInfo.OffPointDetails();
    }

    /**
     * Create an instance of {@link AirFlightInfo.GeneralFlightInfo.FlightTypeDetails }
     * 
     */
    public AirFlightInfo.GeneralFlightInfo.FlightTypeDetails createAirFlightInfoGeneralFlightInfoFlightTypeDetails() {
        return new AirFlightInfo.GeneralFlightInfo.FlightTypeDetails();
    }

    /**
     * Create an instance of {@link AirFlightInfo.GeneralFlightInfo.FlightIdentification }
     * 
     */
    public AirFlightInfo.GeneralFlightInfo.FlightIdentification createAirFlightInfoGeneralFlightInfoFlightIdentification() {
        return new AirFlightInfo.GeneralFlightInfo.FlightIdentification();
    }

    /**
     * Create an instance of {@link AirFlightInfo }
     * 
     */
    public AirFlightInfo createAirFlightInfo() {
        return new AirFlightInfo();
    }

    /**
     * Create an instance of {@link AirFlightInfo.GeneralFlightInfo.BoardPointDetails }
     * 
     */
    public AirFlightInfo.GeneralFlightInfo.BoardPointDetails createAirFlightInfoGeneralFlightInfoBoardPointDetails() {
        return new AirFlightInfo.GeneralFlightInfo.BoardPointDetails();
    }

    /**
     * Create an instance of {@link AirFlightInfo.GeneralFlightInfo.CompanyDetails }
     * 
     */
    public AirFlightInfo.GeneralFlightInfo.CompanyDetails createAirFlightInfoGeneralFlightInfoCompanyDetails() {
        return new AirFlightInfo.GeneralFlightInfo.CompanyDetails();
    }

    /**
     * Create an instance of {@link AirFlightInfo.GeneralFlightInfo }
     * 
     */
    public AirFlightInfo.GeneralFlightInfo createAirFlightInfoGeneralFlightInfo() {
        return new AirFlightInfo.GeneralFlightInfo();
    }

    /**
     * Create an instance of {@link AirFlightInfo.GeneralFlightInfo.FlightDate }
     * 
     */
    public AirFlightInfo.GeneralFlightInfo.FlightDate createAirFlightInfoGeneralFlightInfoFlightDate() {
        return new AirFlightInfo.GeneralFlightInfo.FlightDate();
    }

}
