//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.10 at 06:01:13 ���� KST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xml.amadeus.com/IFLIRR_15_2_1A", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.koreanair.common_adapter.altea.vo.inv_advancedgetflightdatareply_15_2_1a;
