//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.11 at 03:15:49 ���� KST 
//


package com.koreanair.common_adapter.altea.vo.salesreports_displaytransactionreportreply_11_1_1a;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="errorGroup" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}ErrorGroupType" minOccurs="0"/>
 *         &lt;element name="transactionReportDataDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="agencyDetails" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}AdditionalBusinessSourceInformationTypeI"/>
 *                   &lt;element name="agentDetails" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}TicketAgentInfoType"/>
 *                   &lt;element name="dateDetails" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}StructuredDateTimeInformationType"/>
 *                   &lt;element name="documentNumber" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}TicketNumberTypeI"/>
 *                   &lt;element name="transaction" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}TransactionInformationForTicketingType"/>
 *                   &lt;element name="documentIdentification" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}ItemNumberTypeI"/>
 *                   &lt;element name="monetaryInfo" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}MonetaryInformationTypeI"/>
 *                   &lt;element name="reservationInformation" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}ReservationControlInformationTypeI" minOccurs="0"/>
 *                   &lt;element name="passengerName" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}TravellerInformationTypeI" minOccurs="0"/>
 *                   &lt;element name="tourCodeDetails" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}TourInformationTypeI" minOccurs="0"/>
 *                   &lt;element name="invoiceDetails" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}DocumentInformationDetailsTypeI" minOccurs="0"/>
 *                   &lt;element name="fopGroup" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}FOPRepresentationType" maxOccurs="3"/>
 *                   &lt;element name="tax" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}TaxTypeI" maxOccurs="3" minOccurs="0"/>
 *                   &lt;element name="fareCalcDetails" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}CodedAttributeType" minOccurs="0"/>
 *                   &lt;element name="pricingIndicator" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}PricingTicketingDetailsTypeI" minOccurs="0"/>
 *                   &lt;element name="referenceData" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}ReferenceInfoType" minOccurs="0"/>
 *                   &lt;element name="feeGroup" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="feeType" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}SelectionDetailsTypeI"/>
 *                             &lt;element name="feeDetails" maxOccurs="99">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="feeSubType" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}SpecificDataInformationTypeI"/>
 *                                       &lt;element name="feeMonetaryInfo" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}MonetaryInformationTypeI_52231S"/>
 *                                       &lt;element name="feeTaxInfo" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}TaxTypeI" maxOccurs="99" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="exchangedGroup" maxOccurs="99" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ticketExchanged" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}TicketNumberTypeI_63924S"/>
 *                             &lt;element name="couponAssociated" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}CouponInformationType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "errorGroup",
    "transactionReportDataDetails"
})
@XmlRootElement(name = "SalesReports_DisplayTransactionReportReply")
public class SalesReportsDisplayTransactionReportReply {

    protected ErrorGroupType errorGroup;
    protected SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails transactionReportDataDetails;

    /**
     * Gets the value of the errorGroup property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorGroupType }
     *     
     */
    public ErrorGroupType getErrorGroup() {
        return errorGroup;
    }

    /**
     * Sets the value of the errorGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorGroupType }
     *     
     */
    public void setErrorGroup(ErrorGroupType value) {
        this.errorGroup = value;
    }

    /**
     * Gets the value of the transactionReportDataDetails property.
     * 
     * @return
     *     possible object is
     *     {@link SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails }
     *     
     */
    public SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails getTransactionReportDataDetails() {
        return transactionReportDataDetails;
    }

    /**
     * Sets the value of the transactionReportDataDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails }
     *     
     */
    public void setTransactionReportDataDetails(SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails value) {
        this.transactionReportDataDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="agencyDetails" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}AdditionalBusinessSourceInformationTypeI"/>
     *         &lt;element name="agentDetails" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}TicketAgentInfoType"/>
     *         &lt;element name="dateDetails" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}StructuredDateTimeInformationType"/>
     *         &lt;element name="documentNumber" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}TicketNumberTypeI"/>
     *         &lt;element name="transaction" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}TransactionInformationForTicketingType"/>
     *         &lt;element name="documentIdentification" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}ItemNumberTypeI"/>
     *         &lt;element name="monetaryInfo" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}MonetaryInformationTypeI"/>
     *         &lt;element name="reservationInformation" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}ReservationControlInformationTypeI" minOccurs="0"/>
     *         &lt;element name="passengerName" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}TravellerInformationTypeI" minOccurs="0"/>
     *         &lt;element name="tourCodeDetails" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}TourInformationTypeI" minOccurs="0"/>
     *         &lt;element name="invoiceDetails" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}DocumentInformationDetailsTypeI" minOccurs="0"/>
     *         &lt;element name="fopGroup" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}FOPRepresentationType" maxOccurs="3"/>
     *         &lt;element name="tax" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}TaxTypeI" maxOccurs="3" minOccurs="0"/>
     *         &lt;element name="fareCalcDetails" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}CodedAttributeType" minOccurs="0"/>
     *         &lt;element name="pricingIndicator" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}PricingTicketingDetailsTypeI" minOccurs="0"/>
     *         &lt;element name="referenceData" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}ReferenceInfoType" minOccurs="0"/>
     *         &lt;element name="feeGroup" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="feeType" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}SelectionDetailsTypeI"/>
     *                   &lt;element name="feeDetails" maxOccurs="99">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="feeSubType" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}SpecificDataInformationTypeI"/>
     *                             &lt;element name="feeMonetaryInfo" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}MonetaryInformationTypeI_52231S"/>
     *                             &lt;element name="feeTaxInfo" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}TaxTypeI" maxOccurs="99" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="exchangedGroup" maxOccurs="99" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ticketExchanged" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}TicketNumberTypeI_63924S"/>
     *                   &lt;element name="couponAssociated" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}CouponInformationType" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "agencyDetails",
        "agentDetails",
        "dateDetails",
        "documentNumber",
        "transaction",
        "documentIdentification",
        "monetaryInfo",
        "reservationInformation",
        "passengerName",
        "tourCodeDetails",
        "invoiceDetails",
        "fopGroup",
        "tax",
        "fareCalcDetails",
        "pricingIndicator",
        "referenceData",
        "feeGroup",
        "exchangedGroup"
    })
    public static class TransactionReportDataDetails {

        @XmlElement(required = true)
        protected AdditionalBusinessSourceInformationTypeI agencyDetails;
        @XmlElement(required = true)
        protected TicketAgentInfoType agentDetails;
        @XmlElement(required = true)
        protected StructuredDateTimeInformationType dateDetails;
        @XmlElement(required = true)
        protected TicketNumberTypeI documentNumber;
        @XmlElement(required = true)
        protected TransactionInformationForTicketingType transaction;
        @XmlElement(required = true)
        protected ItemNumberTypeI documentIdentification;
        @XmlElement(required = true)
        protected MonetaryInformationTypeI monetaryInfo;
        protected ReservationControlInformationTypeI reservationInformation;
        protected TravellerInformationTypeI passengerName;
        protected TourInformationTypeI tourCodeDetails;
        protected DocumentInformationDetailsTypeI invoiceDetails;
        @XmlElement(required = true)
        protected List<FOPRepresentationType> fopGroup;
        protected List<TaxTypeI> tax;
        protected CodedAttributeType fareCalcDetails;
        protected PricingTicketingDetailsTypeI pricingIndicator;
        protected ReferenceInfoType referenceData;
        protected SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.FeeGroup feeGroup;
        protected List<SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.ExchangedGroup> exchangedGroup;

        /**
         * Gets the value of the agencyDetails property.
         * 
         * @return
         *     possible object is
         *     {@link AdditionalBusinessSourceInformationTypeI }
         *     
         */
        public AdditionalBusinessSourceInformationTypeI getAgencyDetails() {
            return agencyDetails;
        }

        /**
         * Sets the value of the agencyDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link AdditionalBusinessSourceInformationTypeI }
         *     
         */
        public void setAgencyDetails(AdditionalBusinessSourceInformationTypeI value) {
            this.agencyDetails = value;
        }

        /**
         * Gets the value of the agentDetails property.
         * 
         * @return
         *     possible object is
         *     {@link TicketAgentInfoType }
         *     
         */
        public TicketAgentInfoType getAgentDetails() {
            return agentDetails;
        }

        /**
         * Sets the value of the agentDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link TicketAgentInfoType }
         *     
         */
        public void setAgentDetails(TicketAgentInfoType value) {
            this.agentDetails = value;
        }

        /**
         * Gets the value of the dateDetails property.
         * 
         * @return
         *     possible object is
         *     {@link StructuredDateTimeInformationType }
         *     
         */
        public StructuredDateTimeInformationType getDateDetails() {
            return dateDetails;
        }

        /**
         * Sets the value of the dateDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link StructuredDateTimeInformationType }
         *     
         */
        public void setDateDetails(StructuredDateTimeInformationType value) {
            this.dateDetails = value;
        }

        /**
         * Gets the value of the documentNumber property.
         * 
         * @return
         *     possible object is
         *     {@link TicketNumberTypeI }
         *     
         */
        public TicketNumberTypeI getDocumentNumber() {
            return documentNumber;
        }

        /**
         * Sets the value of the documentNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link TicketNumberTypeI }
         *     
         */
        public void setDocumentNumber(TicketNumberTypeI value) {
            this.documentNumber = value;
        }

        /**
         * Gets the value of the transaction property.
         * 
         * @return
         *     possible object is
         *     {@link TransactionInformationForTicketingType }
         *     
         */
        public TransactionInformationForTicketingType getTransaction() {
            return transaction;
        }

        /**
         * Sets the value of the transaction property.
         * 
         * @param value
         *     allowed object is
         *     {@link TransactionInformationForTicketingType }
         *     
         */
        public void setTransaction(TransactionInformationForTicketingType value) {
            this.transaction = value;
        }

        /**
         * Gets the value of the documentIdentification property.
         * 
         * @return
         *     possible object is
         *     {@link ItemNumberTypeI }
         *     
         */
        public ItemNumberTypeI getDocumentIdentification() {
            return documentIdentification;
        }

        /**
         * Sets the value of the documentIdentification property.
         * 
         * @param value
         *     allowed object is
         *     {@link ItemNumberTypeI }
         *     
         */
        public void setDocumentIdentification(ItemNumberTypeI value) {
            this.documentIdentification = value;
        }

        /**
         * Gets the value of the monetaryInfo property.
         * 
         * @return
         *     possible object is
         *     {@link MonetaryInformationTypeI }
         *     
         */
        public MonetaryInformationTypeI getMonetaryInfo() {
            return monetaryInfo;
        }

        /**
         * Sets the value of the monetaryInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link MonetaryInformationTypeI }
         *     
         */
        public void setMonetaryInfo(MonetaryInformationTypeI value) {
            this.monetaryInfo = value;
        }

        /**
         * Gets the value of the reservationInformation property.
         * 
         * @return
         *     possible object is
         *     {@link ReservationControlInformationTypeI }
         *     
         */
        public ReservationControlInformationTypeI getReservationInformation() {
            return reservationInformation;
        }

        /**
         * Sets the value of the reservationInformation property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReservationControlInformationTypeI }
         *     
         */
        public void setReservationInformation(ReservationControlInformationTypeI value) {
            this.reservationInformation = value;
        }

        /**
         * Gets the value of the passengerName property.
         * 
         * @return
         *     possible object is
         *     {@link TravellerInformationTypeI }
         *     
         */
        public TravellerInformationTypeI getPassengerName() {
            return passengerName;
        }

        /**
         * Sets the value of the passengerName property.
         * 
         * @param value
         *     allowed object is
         *     {@link TravellerInformationTypeI }
         *     
         */
        public void setPassengerName(TravellerInformationTypeI value) {
            this.passengerName = value;
        }

        /**
         * Gets the value of the tourCodeDetails property.
         * 
         * @return
         *     possible object is
         *     {@link TourInformationTypeI }
         *     
         */
        public TourInformationTypeI getTourCodeDetails() {
            return tourCodeDetails;
        }

        /**
         * Sets the value of the tourCodeDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link TourInformationTypeI }
         *     
         */
        public void setTourCodeDetails(TourInformationTypeI value) {
            this.tourCodeDetails = value;
        }

        /**
         * Gets the value of the invoiceDetails property.
         * 
         * @return
         *     possible object is
         *     {@link DocumentInformationDetailsTypeI }
         *     
         */
        public DocumentInformationDetailsTypeI getInvoiceDetails() {
            return invoiceDetails;
        }

        /**
         * Sets the value of the invoiceDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link DocumentInformationDetailsTypeI }
         *     
         */
        public void setInvoiceDetails(DocumentInformationDetailsTypeI value) {
            this.invoiceDetails = value;
        }

        /**
         * Gets the value of the fopGroup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fopGroup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFopGroup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FOPRepresentationType }
         * 
         * 
         */
        public List<FOPRepresentationType> getFopGroup() {
            if (fopGroup == null) {
                fopGroup = new ArrayList<FOPRepresentationType>();
            }
            return this.fopGroup;
        }

        /**
         * Gets the value of the tax property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tax property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTax().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TaxTypeI }
         * 
         * 
         */
        public List<TaxTypeI> getTax() {
            if (tax == null) {
                tax = new ArrayList<TaxTypeI>();
            }
            return this.tax;
        }

        /**
         * Gets the value of the fareCalcDetails property.
         * 
         * @return
         *     possible object is
         *     {@link CodedAttributeType }
         *     
         */
        public CodedAttributeType getFareCalcDetails() {
            return fareCalcDetails;
        }

        /**
         * Sets the value of the fareCalcDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodedAttributeType }
         *     
         */
        public void setFareCalcDetails(CodedAttributeType value) {
            this.fareCalcDetails = value;
        }

        /**
         * Gets the value of the pricingIndicator property.
         * 
         * @return
         *     possible object is
         *     {@link PricingTicketingDetailsTypeI }
         *     
         */
        public PricingTicketingDetailsTypeI getPricingIndicator() {
            return pricingIndicator;
        }

        /**
         * Sets the value of the pricingIndicator property.
         * 
         * @param value
         *     allowed object is
         *     {@link PricingTicketingDetailsTypeI }
         *     
         */
        public void setPricingIndicator(PricingTicketingDetailsTypeI value) {
            this.pricingIndicator = value;
        }

        /**
         * Gets the value of the referenceData property.
         * 
         * @return
         *     possible object is
         *     {@link ReferenceInfoType }
         *     
         */
        public ReferenceInfoType getReferenceData() {
            return referenceData;
        }

        /**
         * Sets the value of the referenceData property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReferenceInfoType }
         *     
         */
        public void setReferenceData(ReferenceInfoType value) {
            this.referenceData = value;
        }

        /**
         * Gets the value of the feeGroup property.
         * 
         * @return
         *     possible object is
         *     {@link SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.FeeGroup }
         *     
         */
        public SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.FeeGroup getFeeGroup() {
            return feeGroup;
        }

        /**
         * Sets the value of the feeGroup property.
         * 
         * @param value
         *     allowed object is
         *     {@link SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.FeeGroup }
         *     
         */
        public void setFeeGroup(SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.FeeGroup value) {
            this.feeGroup = value;
        }

        /**
         * Gets the value of the exchangedGroup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the exchangedGroup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExchangedGroup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.ExchangedGroup }
         * 
         * 
         */
        public List<SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.ExchangedGroup> getExchangedGroup() {
            if (exchangedGroup == null) {
                exchangedGroup = new ArrayList<SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.ExchangedGroup>();
            }
            return this.exchangedGroup;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ticketExchanged" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}TicketNumberTypeI_63924S"/>
         *         &lt;element name="couponAssociated" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}CouponInformationType" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ticketExchanged",
            "couponAssociated"
        })
        public static class ExchangedGroup {

            @XmlElement(required = true)
            protected TicketNumberTypeI63924S ticketExchanged;
            protected CouponInformationType couponAssociated;

            /**
             * Gets the value of the ticketExchanged property.
             * 
             * @return
             *     possible object is
             *     {@link TicketNumberTypeI63924S }
             *     
             */
            public TicketNumberTypeI63924S getTicketExchanged() {
                return ticketExchanged;
            }

            /**
             * Sets the value of the ticketExchanged property.
             * 
             * @param value
             *     allowed object is
             *     {@link TicketNumberTypeI63924S }
             *     
             */
            public void setTicketExchanged(TicketNumberTypeI63924S value) {
                this.ticketExchanged = value;
            }

            /**
             * Gets the value of the couponAssociated property.
             * 
             * @return
             *     possible object is
             *     {@link CouponInformationType }
             *     
             */
            public CouponInformationType getCouponAssociated() {
                return couponAssociated;
            }

            /**
             * Sets the value of the couponAssociated property.
             * 
             * @param value
             *     allowed object is
             *     {@link CouponInformationType }
             *     
             */
            public void setCouponAssociated(CouponInformationType value) {
                this.couponAssociated = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="feeType" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}SelectionDetailsTypeI"/>
         *         &lt;element name="feeDetails" maxOccurs="99">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="feeSubType" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}SpecificDataInformationTypeI"/>
         *                   &lt;element name="feeMonetaryInfo" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}MonetaryInformationTypeI_52231S"/>
         *                   &lt;element name="feeTaxInfo" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}TaxTypeI" maxOccurs="99" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "feeType",
            "feeDetails"
        })
        public static class FeeGroup {

            @XmlElement(required = true)
            protected SelectionDetailsTypeI feeType;
            @XmlElement(required = true)
            protected List<SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.FeeGroup.FeeDetails> feeDetails;

            /**
             * Gets the value of the feeType property.
             * 
             * @return
             *     possible object is
             *     {@link SelectionDetailsTypeI }
             *     
             */
            public SelectionDetailsTypeI getFeeType() {
                return feeType;
            }

            /**
             * Sets the value of the feeType property.
             * 
             * @param value
             *     allowed object is
             *     {@link SelectionDetailsTypeI }
             *     
             */
            public void setFeeType(SelectionDetailsTypeI value) {
                this.feeType = value;
            }

            /**
             * Gets the value of the feeDetails property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the feeDetails property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFeeDetails().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.FeeGroup.FeeDetails }
             * 
             * 
             */
            public List<SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.FeeGroup.FeeDetails> getFeeDetails() {
                if (feeDetails == null) {
                    feeDetails = new ArrayList<SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.FeeGroup.FeeDetails>();
                }
                return this.feeDetails;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="feeSubType" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}SpecificDataInformationTypeI"/>
             *         &lt;element name="feeMonetaryInfo" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}MonetaryInformationTypeI_52231S"/>
             *         &lt;element name="feeTaxInfo" type="{http://xml.amadeus.com/TSRTRR_11_1_1A}TaxTypeI" maxOccurs="99" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "feeSubType",
                "feeMonetaryInfo",
                "feeTaxInfo"
            })
            public static class FeeDetails {

                @XmlElement(required = true)
                protected SpecificDataInformationTypeI feeSubType;
                @XmlElement(required = true)
                protected MonetaryInformationTypeI52231S feeMonetaryInfo;
                protected List<TaxTypeI> feeTaxInfo;

                /**
                 * Gets the value of the feeSubType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link SpecificDataInformationTypeI }
                 *     
                 */
                public SpecificDataInformationTypeI getFeeSubType() {
                    return feeSubType;
                }

                /**
                 * Sets the value of the feeSubType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link SpecificDataInformationTypeI }
                 *     
                 */
                public void setFeeSubType(SpecificDataInformationTypeI value) {
                    this.feeSubType = value;
                }

                /**
                 * Gets the value of the feeMonetaryInfo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link MonetaryInformationTypeI52231S }
                 *     
                 */
                public MonetaryInformationTypeI52231S getFeeMonetaryInfo() {
                    return feeMonetaryInfo;
                }

                /**
                 * Sets the value of the feeMonetaryInfo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link MonetaryInformationTypeI52231S }
                 *     
                 */
                public void setFeeMonetaryInfo(MonetaryInformationTypeI52231S value) {
                    this.feeMonetaryInfo = value;
                }

                /**
                 * Gets the value of the feeTaxInfo property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the feeTaxInfo property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getFeeTaxInfo().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link TaxTypeI }
                 * 
                 * 
                 */
                public List<TaxTypeI> getFeeTaxInfo() {
                    if (feeTaxInfo == null) {
                        feeTaxInfo = new ArrayList<TaxTypeI>();
                    }
                    return this.feeTaxInfo;
                }

            }

        }

    }

}
