version: '2.1'

services:
  ms-sample-account:
    image: ms-sample-account:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8080:8081
      - 5005:5005
    