//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.10 at 05:59:00 ���� KST 
//


package com.koreanair.common_adapter.altea.vo.inv_advancedgetflightdata_15_2_1a;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="flightDate" type="{http://xml.amadeus.com/IFLIRQ_15_2_1A}FlightDetailsQueryType"/>
 *         &lt;element name="grabLock" type="{http://xml.amadeus.com/IFLIRQ_15_2_1A}StatusTypeI"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "flightDate",
    "grabLock"
})
@XmlRootElement(name = "Inv_AdvancedGetFlightData")
public class InvAdvancedGetFlightData {

    @XmlElement(required = true)
    protected FlightDetailsQueryType flightDate;
    @XmlElement(required = true)
    protected StatusTypeI grabLock;

    /**
     * Gets the value of the flightDate property.
     * 
     * @return
     *     possible object is
     *     {@link FlightDetailsQueryType }
     *     
     */
    public FlightDetailsQueryType getFlightDate() {
        return flightDate;
    }

    /**
     * Sets the value of the flightDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightDetailsQueryType }
     *     
     */
    public void setFlightDate(FlightDetailsQueryType value) {
        this.flightDate = value;
    }

    /**
     * Gets the value of the grabLock property.
     * 
     * @return
     *     possible object is
     *     {@link StatusTypeI }
     *     
     */
    public StatusTypeI getGrabLock() {
        return grabLock;
    }

    /**
     * Sets the value of the grabLock property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusTypeI }
     *     
     */
    public void setGrabLock(StatusTypeI value) {
        this.grabLock = value;
    }

}
