//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 10:02:58 AM KST 
//


package com.koreanair.common_external.altea.vo.ticket_createtsmfrompricingreply_09_1_1a;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * To provide error free text information.
 * 
 * <p>Java class for InteractiveFreeTextTypeI complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InteractiveFreeTextTypeI">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="errorFreeText" type="{http://xml.amadeus.com/TAUSCR_09_1_1A}AlphaNumericString_Length1To70" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InteractiveFreeTextTypeI", propOrder = {
    "errorFreeText"
})
public class InteractiveFreeTextTypeI {

    protected String errorFreeText;

    /**
     * Gets the value of the errorFreeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorFreeText() {
        return errorFreeText;
    }

    /**
     * Sets the value of the errorFreeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorFreeText(String value) {
        this.errorFreeText = value;
    }

}
