//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.05 at 06:48:23 ���� KST 
//


package com.koreanair.common_external.altea.vo.pnr_upgraderedemptionreply_13_1_1a;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pnrInfo" type="{http://xml.amadeus.com/FFURES_13_1_1A}ReservationControlInformationTypeI" minOccurs="0"/>
 *         &lt;element name="errorGroup" type="{http://xml.amadeus.com/FFURES_13_1_1A}ErrorGroupType" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="ssrGroup" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fqtvData" type="{http://xml.amadeus.com/FFURES_13_1_1A}FrequentTravellerVerificationTypeI"/>
 *                   &lt;element name="actionCode" type="{http://xml.amadeus.com/FFURES_13_1_1A}RelatedProductInformationTypeI" minOccurs="0"/>
 *                   &lt;element name="redemptionReason" type="{http://xml.amadeus.com/FFURES_13_1_1A}InteractiveFreeTextTypeI_14378S" minOccurs="0"/>
 *                   &lt;element name="discountInformation" type="{http://xml.amadeus.com/FFURES_13_1_1A}DiscountInformationType" minOccurs="0"/>
 *                   &lt;element name="bookingClassInformation" type="{http://xml.amadeus.com/FFURES_13_1_1A}ProductInformationType" minOccurs="0"/>
 *                   &lt;element name="errorGroup" type="{http://xml.amadeus.com/FFURES_13_1_1A}ErrorGroupType" maxOccurs="2" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="paxInfoGroup" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="paxInfo" type="{http://xml.amadeus.com/FFURES_13_1_1A}TravellerInformationTypeI"/>
 *                   &lt;element name="ssrGroup">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fqtvData" type="{http://xml.amadeus.com/FFURES_13_1_1A}FrequentTravellerVerificationTypeI"/>
 *                             &lt;element name="actionCode" type="{http://xml.amadeus.com/FFURES_13_1_1A}RelatedProductInformationTypeI" minOccurs="0"/>
 *                             &lt;element name="redemptionReason" type="{http://xml.amadeus.com/FFURES_13_1_1A}InteractiveFreeTextTypeI_14378S" minOccurs="0"/>
 *                             &lt;element name="discountInformation" type="{http://xml.amadeus.com/FFURES_13_1_1A}DiscountInformationType" minOccurs="0"/>
 *                             &lt;element name="bookingClassInformation" type="{http://xml.amadeus.com/FFURES_13_1_1A}ProductInformationType" minOccurs="0"/>
 *                             &lt;element name="errorGroup" type="{http://xml.amadeus.com/FFURES_13_1_1A}ErrorGroupType" maxOccurs="2" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="segInfoGroup" maxOccurs="99" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="segInfo" type="{http://xml.amadeus.com/FFURES_13_1_1A}TravelProductInformationTypeI"/>
 *                   &lt;element name="paxInfoGroup">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="paxInfo" type="{http://xml.amadeus.com/FFURES_13_1_1A}TravellerInformationTypeI"/>
 *                             &lt;element name="ssrGroup">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="fqtvData" type="{http://xml.amadeus.com/FFURES_13_1_1A}FrequentTravellerVerificationTypeI"/>
 *                                       &lt;element name="actionCode" type="{http://xml.amadeus.com/FFURES_13_1_1A}RelatedProductInformationTypeI" minOccurs="0"/>
 *                                       &lt;element name="redemptionReason" type="{http://xml.amadeus.com/FFURES_13_1_1A}InteractiveFreeTextTypeI_14378S" minOccurs="0"/>
 *                                       &lt;element name="discountInformation" type="{http://xml.amadeus.com/FFURES_13_1_1A}DiscountInformationType" minOccurs="0"/>
 *                                       &lt;element name="bookingClassInformation" type="{http://xml.amadeus.com/FFURES_13_1_1A}ProductInformationType" minOccurs="0"/>
 *                                       &lt;element name="errorGroup" type="{http://xml.amadeus.com/FFURES_13_1_1A}ErrorGroupType" maxOccurs="2" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pnrInfo",
    "errorGroup",
    "ssrGroup",
    "paxInfoGroup",
    "segInfoGroup"
})
@XmlRootElement(name = "PNR_UpgradeRedemptionReply")
public class PNRUpgradeRedemptionReply {

    protected ReservationControlInformationTypeI pnrInfo;
    protected List<ErrorGroupType> errorGroup;
    protected SsrGroup ssrGroup;
    protected PaxInfoGroup paxInfoGroup;
    protected List<SegInfoGroup> segInfoGroup;

    /**
     * Gets the value of the pnrInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ReservationControlInformationTypeI }
     *     
     */
    public ReservationControlInformationTypeI getPnrInfo() {
        return pnrInfo;
    }

    /**
     * Sets the value of the pnrInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReservationControlInformationTypeI }
     *     
     */
    public void setPnrInfo(ReservationControlInformationTypeI value) {
        this.pnrInfo = value;
    }

    /**
     * Gets the value of the errorGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the errorGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErrorGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorGroupType }
     * 
     * 
     */
    public List<ErrorGroupType> getErrorGroup() {
        if (errorGroup == null) {
            errorGroup = new ArrayList<ErrorGroupType>();
        }
        return this.errorGroup;
    }

    /**
     * Gets the value of the ssrGroup property.
     * 
     * @return
     *     possible object is
     *     {@link SsrGroup }
     *     
     */
    public SsrGroup getSsrGroup() {
        return ssrGroup;
    }

    /**
     * Sets the value of the ssrGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link SsrGroup }
     *     
     */
    public void setSsrGroup(SsrGroup value) {
        this.ssrGroup = value;
    }

    /**
     * Gets the value of the paxInfoGroup property.
     * 
     * @return
     *     possible object is
     *     {@link PaxInfoGroup }
     *     
     */
    public PaxInfoGroup getPaxInfoGroup() {
        return paxInfoGroup;
    }

    /**
     * Sets the value of the paxInfoGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaxInfoGroup }
     *     
     */
    public void setPaxInfoGroup(PaxInfoGroup value) {
        this.paxInfoGroup = value;
    }

    /**
     * Gets the value of the segInfoGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the segInfoGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegInfoGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SegInfoGroup }
     * 
     * 
     */
    public List<SegInfoGroup> getSegInfoGroup() {
        if (segInfoGroup == null) {
            segInfoGroup = new ArrayList<SegInfoGroup>();
        }
        return this.segInfoGroup;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="paxInfo" type="{http://xml.amadeus.com/FFURES_13_1_1A}TravellerInformationTypeI"/>
     *         &lt;element name="ssrGroup">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="fqtvData" type="{http://xml.amadeus.com/FFURES_13_1_1A}FrequentTravellerVerificationTypeI"/>
     *                   &lt;element name="actionCode" type="{http://xml.amadeus.com/FFURES_13_1_1A}RelatedProductInformationTypeI" minOccurs="0"/>
     *                   &lt;element name="redemptionReason" type="{http://xml.amadeus.com/FFURES_13_1_1A}InteractiveFreeTextTypeI_14378S" minOccurs="0"/>
     *                   &lt;element name="discountInformation" type="{http://xml.amadeus.com/FFURES_13_1_1A}DiscountInformationType" minOccurs="0"/>
     *                   &lt;element name="bookingClassInformation" type="{http://xml.amadeus.com/FFURES_13_1_1A}ProductInformationType" minOccurs="0"/>
     *                   &lt;element name="errorGroup" type="{http://xml.amadeus.com/FFURES_13_1_1A}ErrorGroupType" maxOccurs="2" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "paxInfo",
        "ssrGroup"
    })
    public static class PaxInfoGroup {

        @XmlElement(required = true)
        protected TravellerInformationTypeI paxInfo;
        @XmlElement(required = true)
        protected PNRUpgradeRedemptionReply.PaxInfoGroup.SsrGroup ssrGroup;

        /**
         * Gets the value of the paxInfo property.
         * 
         * @return
         *     possible object is
         *     {@link TravellerInformationTypeI }
         *     
         */
        public TravellerInformationTypeI getPaxInfo() {
            return paxInfo;
        }

        /**
         * Sets the value of the paxInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link TravellerInformationTypeI }
         *     
         */
        public void setPaxInfo(TravellerInformationTypeI value) {
            this.paxInfo = value;
        }

        /**
         * Gets the value of the ssrGroup property.
         * 
         * @return
         *     possible object is
         *     {@link SsrGroup }
         *     
         */
        public SsrGroup getSsrGroup() {
            return ssrGroup;
        }

        /**
         * Sets the value of the ssrGroup property.
         * 
         * @param value
         *     allowed object is
         *     {@link SsrGroup }
         *     
         */
        public void setSsrGroup(SsrGroup value) {
            this.ssrGroup = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="fqtvData" type="{http://xml.amadeus.com/FFURES_13_1_1A}FrequentTravellerVerificationTypeI"/>
         *         &lt;element name="actionCode" type="{http://xml.amadeus.com/FFURES_13_1_1A}RelatedProductInformationTypeI" minOccurs="0"/>
         *         &lt;element name="redemptionReason" type="{http://xml.amadeus.com/FFURES_13_1_1A}InteractiveFreeTextTypeI_14378S" minOccurs="0"/>
         *         &lt;element name="discountInformation" type="{http://xml.amadeus.com/FFURES_13_1_1A}DiscountInformationType" minOccurs="0"/>
         *         &lt;element name="bookingClassInformation" type="{http://xml.amadeus.com/FFURES_13_1_1A}ProductInformationType" minOccurs="0"/>
         *         &lt;element name="errorGroup" type="{http://xml.amadeus.com/FFURES_13_1_1A}ErrorGroupType" maxOccurs="2" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fqtvData",
            "actionCode",
            "redemptionReason",
            "discountInformation",
            "bookingClassInformation",
            "errorGroup"
        })
        public static class SsrGroup {

            @XmlElement(required = true)
            protected FrequentTravellerVerificationTypeI fqtvData;
            protected RelatedProductInformationTypeI actionCode;
            protected InteractiveFreeTextTypeI14378S redemptionReason;
            protected DiscountInformationType discountInformation;
            protected ProductInformationType bookingClassInformation;
            protected List<ErrorGroupType> errorGroup;

            /**
             * Gets the value of the fqtvData property.
             * 
             * @return
             *     possible object is
             *     {@link FrequentTravellerVerificationTypeI }
             *     
             */
            public FrequentTravellerVerificationTypeI getFqtvData() {
                return fqtvData;
            }

            /**
             * Sets the value of the fqtvData property.
             * 
             * @param value
             *     allowed object is
             *     {@link FrequentTravellerVerificationTypeI }
             *     
             */
            public void setFqtvData(FrequentTravellerVerificationTypeI value) {
                this.fqtvData = value;
            }

            /**
             * Gets the value of the actionCode property.
             * 
             * @return
             *     possible object is
             *     {@link RelatedProductInformationTypeI }
             *     
             */
            public RelatedProductInformationTypeI getActionCode() {
                return actionCode;
            }

            /**
             * Sets the value of the actionCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link RelatedProductInformationTypeI }
             *     
             */
            public void setActionCode(RelatedProductInformationTypeI value) {
                this.actionCode = value;
            }

            /**
             * Gets the value of the redemptionReason property.
             * 
             * @return
             *     possible object is
             *     {@link InteractiveFreeTextTypeI14378S }
             *     
             */
            public InteractiveFreeTextTypeI14378S getRedemptionReason() {
                return redemptionReason;
            }

            /**
             * Sets the value of the redemptionReason property.
             * 
             * @param value
             *     allowed object is
             *     {@link InteractiveFreeTextTypeI14378S }
             *     
             */
            public void setRedemptionReason(InteractiveFreeTextTypeI14378S value) {
                this.redemptionReason = value;
            }

            /**
             * Gets the value of the discountInformation property.
             * 
             * @return
             *     possible object is
             *     {@link DiscountInformationType }
             *     
             */
            public DiscountInformationType getDiscountInformation() {
                return discountInformation;
            }

            /**
             * Sets the value of the discountInformation property.
             * 
             * @param value
             *     allowed object is
             *     {@link DiscountInformationType }
             *     
             */
            public void setDiscountInformation(DiscountInformationType value) {
                this.discountInformation = value;
            }

            /**
             * Gets the value of the bookingClassInformation property.
             * 
             * @return
             *     possible object is
             *     {@link ProductInformationType }
             *     
             */
            public ProductInformationType getBookingClassInformation() {
                return bookingClassInformation;
            }

            /**
             * Sets the value of the bookingClassInformation property.
             * 
             * @param value
             *     allowed object is
             *     {@link ProductInformationType }
             *     
             */
            public void setBookingClassInformation(ProductInformationType value) {
                this.bookingClassInformation = value;
            }

            /**
             * Gets the value of the errorGroup property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the errorGroup property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getErrorGroup().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ErrorGroupType }
             * 
             * 
             */
            public List<ErrorGroupType> getErrorGroup() {
                if (errorGroup == null) {
                    errorGroup = new ArrayList<ErrorGroupType>();
                }
                return this.errorGroup;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="segInfo" type="{http://xml.amadeus.com/FFURES_13_1_1A}TravelProductInformationTypeI"/>
     *         &lt;element name="paxInfoGroup">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="paxInfo" type="{http://xml.amadeus.com/FFURES_13_1_1A}TravellerInformationTypeI"/>
     *                   &lt;element name="ssrGroup">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="fqtvData" type="{http://xml.amadeus.com/FFURES_13_1_1A}FrequentTravellerVerificationTypeI"/>
     *                             &lt;element name="actionCode" type="{http://xml.amadeus.com/FFURES_13_1_1A}RelatedProductInformationTypeI" minOccurs="0"/>
     *                             &lt;element name="redemptionReason" type="{http://xml.amadeus.com/FFURES_13_1_1A}InteractiveFreeTextTypeI_14378S" minOccurs="0"/>
     *                             &lt;element name="discountInformation" type="{http://xml.amadeus.com/FFURES_13_1_1A}DiscountInformationType" minOccurs="0"/>
     *                             &lt;element name="bookingClassInformation" type="{http://xml.amadeus.com/FFURES_13_1_1A}ProductInformationType" minOccurs="0"/>
     *                             &lt;element name="errorGroup" type="{http://xml.amadeus.com/FFURES_13_1_1A}ErrorGroupType" maxOccurs="2" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "segInfo",
        "paxInfoGroup"
    })
    public static class SegInfoGroup {

        @XmlElement(required = true)
        protected TravelProductInformationTypeI segInfo;
        @XmlElement(required = true)
        protected PNRUpgradeRedemptionReply.SegInfoGroup.PaxInfoGroup paxInfoGroup;

        /**
         * Gets the value of the segInfo property.
         * 
         * @return
         *     possible object is
         *     {@link TravelProductInformationTypeI }
         *     
         */
        public TravelProductInformationTypeI getSegInfo() {
            return segInfo;
        }

        /**
         * Sets the value of the segInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link TravelProductInformationTypeI }
         *     
         */
        public void setSegInfo(TravelProductInformationTypeI value) {
            this.segInfo = value;
        }

        /**
         * Gets the value of the paxInfoGroup property.
         * 
         * @return
         *     possible object is
         *     {@link PaxInfoGroup }
         *     
         */
        public PaxInfoGroup getPaxInfoGroup() {
            return paxInfoGroup;
        }

        /**
         * Sets the value of the paxInfoGroup property.
         * 
         * @param value
         *     allowed object is
         *     {@link PaxInfoGroup }
         *     
         */
        public void setPaxInfoGroup(PaxInfoGroup value) {
            this.paxInfoGroup = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="paxInfo" type="{http://xml.amadeus.com/FFURES_13_1_1A}TravellerInformationTypeI"/>
         *         &lt;element name="ssrGroup">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="fqtvData" type="{http://xml.amadeus.com/FFURES_13_1_1A}FrequentTravellerVerificationTypeI"/>
         *                   &lt;element name="actionCode" type="{http://xml.amadeus.com/FFURES_13_1_1A}RelatedProductInformationTypeI" minOccurs="0"/>
         *                   &lt;element name="redemptionReason" type="{http://xml.amadeus.com/FFURES_13_1_1A}InteractiveFreeTextTypeI_14378S" minOccurs="0"/>
         *                   &lt;element name="discountInformation" type="{http://xml.amadeus.com/FFURES_13_1_1A}DiscountInformationType" minOccurs="0"/>
         *                   &lt;element name="bookingClassInformation" type="{http://xml.amadeus.com/FFURES_13_1_1A}ProductInformationType" minOccurs="0"/>
         *                   &lt;element name="errorGroup" type="{http://xml.amadeus.com/FFURES_13_1_1A}ErrorGroupType" maxOccurs="2" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "paxInfo",
            "ssrGroup"
        })
        public static class PaxInfoGroup {

            @XmlElement(required = true)
            protected TravellerInformationTypeI paxInfo;
            @XmlElement(required = true)
            protected PNRUpgradeRedemptionReply.SegInfoGroup.PaxInfoGroup.SsrGroup ssrGroup;

            /**
             * Gets the value of the paxInfo property.
             * 
             * @return
             *     possible object is
             *     {@link TravellerInformationTypeI }
             *     
             */
            public TravellerInformationTypeI getPaxInfo() {
                return paxInfo;
            }

            /**
             * Sets the value of the paxInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link TravellerInformationTypeI }
             *     
             */
            public void setPaxInfo(TravellerInformationTypeI value) {
                this.paxInfo = value;
            }

            /**
             * Gets the value of the ssrGroup property.
             * 
             * @return
             *     possible object is
             *     {@link SsrGroup }
             *     
             */
            public SsrGroup getSsrGroup() {
                return ssrGroup;
            }

            /**
             * Sets the value of the ssrGroup property.
             * 
             * @param value
             *     allowed object is
             *     {@link SsrGroup }
             *     
             */
            public void setSsrGroup(SsrGroup value) {
                this.ssrGroup = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="fqtvData" type="{http://xml.amadeus.com/FFURES_13_1_1A}FrequentTravellerVerificationTypeI"/>
             *         &lt;element name="actionCode" type="{http://xml.amadeus.com/FFURES_13_1_1A}RelatedProductInformationTypeI" minOccurs="0"/>
             *         &lt;element name="redemptionReason" type="{http://xml.amadeus.com/FFURES_13_1_1A}InteractiveFreeTextTypeI_14378S" minOccurs="0"/>
             *         &lt;element name="discountInformation" type="{http://xml.amadeus.com/FFURES_13_1_1A}DiscountInformationType" minOccurs="0"/>
             *         &lt;element name="bookingClassInformation" type="{http://xml.amadeus.com/FFURES_13_1_1A}ProductInformationType" minOccurs="0"/>
             *         &lt;element name="errorGroup" type="{http://xml.amadeus.com/FFURES_13_1_1A}ErrorGroupType" maxOccurs="2" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "fqtvData",
                "actionCode",
                "redemptionReason",
                "discountInformation",
                "bookingClassInformation",
                "errorGroup"
            })
            public static class SsrGroup {

                @XmlElement(required = true)
                protected FrequentTravellerVerificationTypeI fqtvData;
                protected RelatedProductInformationTypeI actionCode;
                protected InteractiveFreeTextTypeI14378S redemptionReason;
                protected DiscountInformationType discountInformation;
                protected ProductInformationType bookingClassInformation;
                protected List<ErrorGroupType> errorGroup;

                /**
                 * Gets the value of the fqtvData property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link FrequentTravellerVerificationTypeI }
                 *     
                 */
                public FrequentTravellerVerificationTypeI getFqtvData() {
                    return fqtvData;
                }

                /**
                 * Sets the value of the fqtvData property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link FrequentTravellerVerificationTypeI }
                 *     
                 */
                public void setFqtvData(FrequentTravellerVerificationTypeI value) {
                    this.fqtvData = value;
                }

                /**
                 * Gets the value of the actionCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link RelatedProductInformationTypeI }
                 *     
                 */
                public RelatedProductInformationTypeI getActionCode() {
                    return actionCode;
                }

                /**
                 * Sets the value of the actionCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link RelatedProductInformationTypeI }
                 *     
                 */
                public void setActionCode(RelatedProductInformationTypeI value) {
                    this.actionCode = value;
                }

                /**
                 * Gets the value of the redemptionReason property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link InteractiveFreeTextTypeI14378S }
                 *     
                 */
                public InteractiveFreeTextTypeI14378S getRedemptionReason() {
                    return redemptionReason;
                }

                /**
                 * Sets the value of the redemptionReason property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link InteractiveFreeTextTypeI14378S }
                 *     
                 */
                public void setRedemptionReason(InteractiveFreeTextTypeI14378S value) {
                    this.redemptionReason = value;
                }

                /**
                 * Gets the value of the discountInformation property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link DiscountInformationType }
                 *     
                 */
                public DiscountInformationType getDiscountInformation() {
                    return discountInformation;
                }

                /**
                 * Sets the value of the discountInformation property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link DiscountInformationType }
                 *     
                 */
                public void setDiscountInformation(DiscountInformationType value) {
                    this.discountInformation = value;
                }

                /**
                 * Gets the value of the bookingClassInformation property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ProductInformationType }
                 *     
                 */
                public ProductInformationType getBookingClassInformation() {
                    return bookingClassInformation;
                }

                /**
                 * Sets the value of the bookingClassInformation property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ProductInformationType }
                 *     
                 */
                public void setBookingClassInformation(ProductInformationType value) {
                    this.bookingClassInformation = value;
                }

                /**
                 * Gets the value of the errorGroup property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the errorGroup property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getErrorGroup().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link ErrorGroupType }
                 * 
                 * 
                 */
                public List<ErrorGroupType> getErrorGroup() {
                    if (errorGroup == null) {
                        errorGroup = new ArrayList<ErrorGroupType>();
                    }
                    return this.errorGroup;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fqtvData" type="{http://xml.amadeus.com/FFURES_13_1_1A}FrequentTravellerVerificationTypeI"/>
     *         &lt;element name="actionCode" type="{http://xml.amadeus.com/FFURES_13_1_1A}RelatedProductInformationTypeI" minOccurs="0"/>
     *         &lt;element name="redemptionReason" type="{http://xml.amadeus.com/FFURES_13_1_1A}InteractiveFreeTextTypeI_14378S" minOccurs="0"/>
     *         &lt;element name="discountInformation" type="{http://xml.amadeus.com/FFURES_13_1_1A}DiscountInformationType" minOccurs="0"/>
     *         &lt;element name="bookingClassInformation" type="{http://xml.amadeus.com/FFURES_13_1_1A}ProductInformationType" minOccurs="0"/>
     *         &lt;element name="errorGroup" type="{http://xml.amadeus.com/FFURES_13_1_1A}ErrorGroupType" maxOccurs="2" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fqtvData",
        "actionCode",
        "redemptionReason",
        "discountInformation",
        "bookingClassInformation",
        "errorGroup"
    })
    public static class SsrGroup {

        @XmlElement(required = true)
        protected FrequentTravellerVerificationTypeI fqtvData;
        protected RelatedProductInformationTypeI actionCode;
        protected InteractiveFreeTextTypeI14378S redemptionReason;
        protected DiscountInformationType discountInformation;
        protected ProductInformationType bookingClassInformation;
        protected List<ErrorGroupType> errorGroup;

        /**
         * Gets the value of the fqtvData property.
         * 
         * @return
         *     possible object is
         *     {@link FrequentTravellerVerificationTypeI }
         *     
         */
        public FrequentTravellerVerificationTypeI getFqtvData() {
            return fqtvData;
        }

        /**
         * Sets the value of the fqtvData property.
         * 
         * @param value
         *     allowed object is
         *     {@link FrequentTravellerVerificationTypeI }
         *     
         */
        public void setFqtvData(FrequentTravellerVerificationTypeI value) {
            this.fqtvData = value;
        }

        /**
         * Gets the value of the actionCode property.
         * 
         * @return
         *     possible object is
         *     {@link RelatedProductInformationTypeI }
         *     
         */
        public RelatedProductInformationTypeI getActionCode() {
            return actionCode;
        }

        /**
         * Sets the value of the actionCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link RelatedProductInformationTypeI }
         *     
         */
        public void setActionCode(RelatedProductInformationTypeI value) {
            this.actionCode = value;
        }

        /**
         * Gets the value of the redemptionReason property.
         * 
         * @return
         *     possible object is
         *     {@link InteractiveFreeTextTypeI14378S }
         *     
         */
        public InteractiveFreeTextTypeI14378S getRedemptionReason() {
            return redemptionReason;
        }

        /**
         * Sets the value of the redemptionReason property.
         * 
         * @param value
         *     allowed object is
         *     {@link InteractiveFreeTextTypeI14378S }
         *     
         */
        public void setRedemptionReason(InteractiveFreeTextTypeI14378S value) {
            this.redemptionReason = value;
        }

        /**
         * Gets the value of the discountInformation property.
         * 
         * @return
         *     possible object is
         *     {@link DiscountInformationType }
         *     
         */
        public DiscountInformationType getDiscountInformation() {
            return discountInformation;
        }

        /**
         * Sets the value of the discountInformation property.
         * 
         * @param value
         *     allowed object is
         *     {@link DiscountInformationType }
         *     
         */
        public void setDiscountInformation(DiscountInformationType value) {
            this.discountInformation = value;
        }

        /**
         * Gets the value of the bookingClassInformation property.
         * 
         * @return
         *     possible object is
         *     {@link ProductInformationType }
         *     
         */
        public ProductInformationType getBookingClassInformation() {
            return bookingClassInformation;
        }

        /**
         * Sets the value of the bookingClassInformation property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProductInformationType }
         *     
         */
        public void setBookingClassInformation(ProductInformationType value) {
            this.bookingClassInformation = value;
        }

        /**
         * Gets the value of the errorGroup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the errorGroup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getErrorGroup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ErrorGroupType }
         * 
         * 
         */
        public List<ErrorGroupType> getErrorGroup() {
            if (errorGroup == null) {
                errorGroup = new ArrayList<ErrorGroupType>();
            }
            return this.errorGroup;
        }

    }

}
