//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.05 at 06:47:52 ���� KST 
//


package com.koreanair.common_adapter.altea.vo.fop_updateformofpayment_12_1_1a;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * References validation data of a INV Fop
 * 
 * <p>Java class for InvoiceValidationGroupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceValidationGroupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="approvalCodeDetails" type="{http://xml.amadeus.com/TFOPUQ_12_1_1A}GenericAuthorisationResultType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceValidationGroupType", propOrder = {
    "approvalCodeDetails"
})
public class InvoiceValidationGroupType {

    @XmlElement(required = true)
    protected GenericAuthorisationResultType approvalCodeDetails;

    /**
     * Gets the value of the approvalCodeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link GenericAuthorisationResultType }
     *     
     */
    public GenericAuthorisationResultType getApprovalCodeDetails() {
        return approvalCodeDetails;
    }

    /**
     * Sets the value of the approvalCodeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericAuthorisationResultType }
     *     
     */
    public void setApprovalCodeDetails(GenericAuthorisationResultType value) {
        this.approvalCodeDetails = value;
    }

}
