//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 05:10:35 ���� KST 
//


package com.koreanair.common_adapter.altea.vo.service_integratedcataloguereply_13_3_1a;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProposedServiceDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProposedServiceDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="proposedServiceDetails" type="{http://xml.amadeus.com/TPICGR_13_3_1A}SpecialRequirementsDetailsType_153073S"/>
 *         &lt;element name="proposedServiceRefInformation" type="{http://xml.amadeus.com/TPICGR_13_3_1A}ReferenceInfoType" minOccurs="0"/>
 *         &lt;element name="proposedServiceProductInfo" type="{http://xml.amadeus.com/TPICGR_13_3_1A}ProductInformationType_153075S" minOccurs="0"/>
 *         &lt;element name="proposedServiceParameters" type="{http://xml.amadeus.com/TPICGR_13_3_1A}SeatRequestParametersTypeI" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProposedServiceDetailsType", propOrder = {
    "proposedServiceDetails",
    "proposedServiceRefInformation",
    "proposedServiceProductInfo",
    "proposedServiceParameters"
})
public class ProposedServiceDetailsType {

    @XmlElement(required = true)
    protected SpecialRequirementsDetailsType153073S proposedServiceDetails;
    protected ReferenceInfoType proposedServiceRefInformation;
    protected ProductInformationType153075S proposedServiceProductInfo;
    protected SeatRequestParametersTypeI proposedServiceParameters;

    /**
     * Gets the value of the proposedServiceDetails property.
     * 
     * @return
     *     possible object is
     *     {@link SpecialRequirementsDetailsType153073S }
     *     
     */
    public SpecialRequirementsDetailsType153073S getProposedServiceDetails() {
        return proposedServiceDetails;
    }

    /**
     * Sets the value of the proposedServiceDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecialRequirementsDetailsType153073S }
     *     
     */
    public void setProposedServiceDetails(SpecialRequirementsDetailsType153073S value) {
        this.proposedServiceDetails = value;
    }

    /**
     * Gets the value of the proposedServiceRefInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceInfoType }
     *     
     */
    public ReferenceInfoType getProposedServiceRefInformation() {
        return proposedServiceRefInformation;
    }

    /**
     * Sets the value of the proposedServiceRefInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceInfoType }
     *     
     */
    public void setProposedServiceRefInformation(ReferenceInfoType value) {
        this.proposedServiceRefInformation = value;
    }

    /**
     * Gets the value of the proposedServiceProductInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ProductInformationType153075S }
     *     
     */
    public ProductInformationType153075S getProposedServiceProductInfo() {
        return proposedServiceProductInfo;
    }

    /**
     * Sets the value of the proposedServiceProductInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductInformationType153075S }
     *     
     */
    public void setProposedServiceProductInfo(ProductInformationType153075S value) {
        this.proposedServiceProductInfo = value;
    }

    /**
     * Gets the value of the proposedServiceParameters property.
     * 
     * @return
     *     possible object is
     *     {@link SeatRequestParametersTypeI }
     *     
     */
    public SeatRequestParametersTypeI getProposedServiceParameters() {
        return proposedServiceParameters;
    }

    /**
     * Sets the value of the proposedServiceParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeatRequestParametersTypeI }
     *     
     */
    public void setProposedServiceParameters(SeatRequestParametersTypeI value) {
        this.proposedServiceParameters = value;
    }

}
