//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 06:12:38 ���� KST 
//


package com.koreanair.common_external.altea.vo.service_priceserviceviacatalogue_12_3_1a;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.koreanair.common_external.altea.vo.service_priceserviceviacatalogue_12_3_1a package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.koreanair.common_external.altea.vo.service_priceserviceviacatalogue_12_3_1a
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TaxDetailsType67527S }
     * 
     */
    public TaxDetailsType67527S createTaxDetailsType67527S() {
        return new TaxDetailsType67527S();
    }

    /**
     * Create an instance of {@link SpecificDataInformationType67504S }
     * 
     */
    public SpecificDataInformationType67504S createSpecificDataInformationType67504S() {
        return new SpecificDataInformationType67504S();
    }

    /**
     * Create an instance of {@link LocationType105598C }
     * 
     */
    public LocationType105598C createLocationType105598C() {
        return new LocationType105598C();
    }

    /**
     * Create an instance of {@link FareInformationType67521S }
     * 
     */
    public FareInformationType67521S createFareInformationType67521S() {
        return new FareInformationType67521S();
    }

    /**
     * Create an instance of {@link RelatedProductInformationType }
     * 
     */
    public RelatedProductInformationType createRelatedProductInformationType() {
        return new RelatedProductInformationType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link RequestedSegmentInfoType }
     * 
     */
    public RequestedSegmentInfoType createRequestedSegmentInfoType() {
        return new RequestedSegmentInfoType();
    }

    /**
     * Create an instance of {@link AdditionalFareQualifierDetailsTypeI105601C }
     * 
     */
    public AdditionalFareQualifierDetailsTypeI105601C createAdditionalFareQualifierDetailsTypeI105601C() {
        return new AdditionalFareQualifierDetailsTypeI105601C();
    }

    /**
     * Create an instance of {@link PricingTicketingInformationType }
     * 
     */
    public PricingTicketingInformationType createPricingTicketingInformationType() {
        return new PricingTicketingInformationType();
    }

    /**
     * Create an instance of {@link ReferenceInformationTypeI }
     * 
     */
    public ReferenceInformationTypeI createReferenceInformationTypeI() {
        return new ReferenceInformationTypeI();
    }

    /**
     * Create an instance of {@link ReferencingDetailsTypeI }
     * 
     */
    public ReferencingDetailsTypeI createReferencingDetailsTypeI() {
        return new ReferencingDetailsTypeI();
    }

    /**
     * Create an instance of {@link ConversionRateType }
     * 
     */
    public ConversionRateType createConversionRateType() {
        return new ConversionRateType();
    }

    /**
     * Create an instance of {@link MonetaryInformationDetailsType105571C }
     * 
     */
    public MonetaryInformationDetailsType105571C createMonetaryInformationDetailsType105571C() {
        return new MonetaryInformationDetailsType105571C();
    }

    /**
     * Create an instance of {@link ActionDetailsType }
     * 
     */
    public ActionDetailsType createActionDetailsType() {
        return new ActionDetailsType();
    }

    /**
     * Create an instance of {@link ProductInformationType }
     * 
     */
    public ProductInformationType createProductInformationType() {
        return new ProductInformationType();
    }

    /**
     * Create an instance of {@link SystemDetailsTypeI }
     * 
     */
    public SystemDetailsTypeI createSystemDetailsTypeI() {
        return new SystemDetailsTypeI();
    }

    /**
     * Create an instance of {@link FareComponentDetailsTypeI }
     * 
     */
    public FareComponentDetailsTypeI createFareComponentDetailsTypeI() {
        return new FareComponentDetailsTypeI();
    }

    /**
     * Create an instance of {@link AdditionalFareQualifierDetailsTypeI }
     * 
     */
    public AdditionalFareQualifierDetailsTypeI createAdditionalFareQualifierDetailsTypeI() {
        return new AdditionalFareQualifierDetailsTypeI();
    }

    /**
     * Create an instance of {@link TransportIdentifierTypeI }
     * 
     */
    public TransportIdentifierTypeI createTransportIdentifierTypeI() {
        return new TransportIdentifierTypeI();
    }

    /**
     * Create an instance of {@link LocationType105563C }
     * 
     */
    public LocationType105563C createLocationType105563C() {
        return new LocationType105563C();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link FareProductInfoType }
     * 
     */
    public FareProductInfoType createFareProductInfoType() {
        return new FareProductInfoType();
    }

    /**
     * Create an instance of {@link MarriageControlDetailsType }
     * 
     */
    public MarriageControlDetailsType createMarriageControlDetailsType() {
        return new MarriageControlDetailsType();
    }

    /**
     * Create an instance of {@link DataInformationType }
     * 
     */
    public DataInformationType createDataInformationType() {
        return new DataInformationType();
    }

    /**
     * Create an instance of {@link FareTypeGroupingInformationType }
     * 
     */
    public FareTypeGroupingInformationType createFareTypeGroupingInformationType() {
        return new FareTypeGroupingInformationType();
    }

    /**
     * Create an instance of {@link PassengerFareBasisType }
     * 
     */
    public PassengerFareBasisType createPassengerFareBasisType() {
        return new PassengerFareBasisType();
    }

    /**
     * Create an instance of {@link CompanyIdentificationNumbersTypeI }
     * 
     */
    public CompanyIdentificationNumbersTypeI createCompanyIdentificationNumbersTypeI() {
        return new CompanyIdentificationNumbersTypeI();
    }

    /**
     * Create an instance of {@link ExcessBaggageType }
     * 
     */
    public ExcessBaggageType createExcessBaggageType() {
        return new ExcessBaggageType();
    }

    /**
     * Create an instance of {@link StationInformationTypeI }
     * 
     */
    public StationInformationTypeI createStationInformationTypeI() {
        return new StationInformationTypeI();
    }

    /**
     * Create an instance of {@link QuantityType }
     * 
     */
    public QuantityType createQuantityType() {
        return new QuantityType();
    }

    /**
     * Create an instance of {@link LocationDetailsTypeI105621C }
     * 
     */
    public LocationDetailsTypeI105621C createLocationDetailsTypeI105621C() {
        return new LocationDetailsTypeI105621C();
    }

    /**
     * Create an instance of {@link LocationTypeI }
     * 
     */
    public LocationTypeI createLocationTypeI() {
        return new LocationTypeI();
    }

    /**
     * Create an instance of {@link ProductInformationType67517S }
     * 
     */
    public ProductInformationType67517S createProductInformationType67517S() {
        return new ProductInformationType67517S();
    }

    /**
     * Create an instance of {@link MonetaryInformationType67522S }
     * 
     */
    public MonetaryInformationType67522S createMonetaryInformationType67522S() {
        return new MonetaryInformationType67522S();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link LocationDetailsTypeI105620C }
     * 
     */
    public LocationDetailsTypeI105620C createLocationDetailsTypeI105620C() {
        return new LocationDetailsTypeI105620C();
    }

    /**
     * Create an instance of {@link AdditionalProductInfoType }
     * 
     */
    public AdditionalProductInfoType createAdditionalProductInfoType() {
        return new AdditionalProductInfoType();
    }

    /**
     * Create an instance of {@link ItemNumberIdentificationType }
     * 
     */
    public ItemNumberIdentificationType createItemNumberIdentificationType() {
        return new ItemNumberIdentificationType();
    }

    /**
     * Create an instance of {@link ExcessBaggageDetailsType }
     * 
     */
    public ExcessBaggageDetailsType createExcessBaggageDetailsType() {
        return new ExcessBaggageDetailsType();
    }

    /**
     * Create an instance of {@link TravelProductInformationType67568S }
     * 
     */
    public TravelProductInformationType67568S createTravelProductInformationType67568S() {
        return new TravelProductInformationType67568S();
    }

    /**
     * Create an instance of {@link DateAndTimeDetailsTypeI105637C }
     * 
     */
    public DateAndTimeDetailsTypeI105637C createDateAndTimeDetailsTypeI105637C() {
        return new DateAndTimeDetailsTypeI105637C();
    }

    /**
     * Create an instance of {@link GeneralTicketInfoType }
     * 
     */
    public GeneralTicketInfoType createGeneralTicketInfoType() {
        return new GeneralTicketInfoType();
    }

    /**
     * Create an instance of {@link TaxDetailsType }
     * 
     */
    public TaxDetailsType createTaxDetailsType() {
        return new TaxDetailsType();
    }

    /**
     * Create an instance of {@link DataInformationType159332C }
     * 
     */
    public DataInformationType159332C createDataInformationType159332C() {
        return new DataInformationType159332C();
    }

    /**
     * Create an instance of {@link TaxDetailsType67505S }
     * 
     */
    public TaxDetailsType67505S createTaxDetailsType67505S() {
        return new TaxDetailsType67505S();
    }

    /**
     * Create an instance of {@link MonetaryInformationType67540S }
     * 
     */
    public MonetaryInformationType67540S createMonetaryInformationType67540S() {
        return new MonetaryInformationType67540S();
    }

    /**
     * Create an instance of {@link PassengerListType }
     * 
     */
    public PassengerListType createPassengerListType() {
        return new PassengerListType();
    }

    /**
     * Create an instance of {@link BaggageDetailsTypeI }
     * 
     */
    public BaggageDetailsTypeI createBaggageDetailsTypeI() {
        return new BaggageDetailsTypeI();
    }

    /**
     * Create an instance of {@link ProductIdentificationDetailsType105642C }
     * 
     */
    public ProductIdentificationDetailsType105642C createProductIdentificationDetailsType105642C() {
        return new ProductIdentificationDetailsType105642C();
    }

    /**
     * Create an instance of {@link CouponInformationDetailsTypeI }
     * 
     */
    public CouponInformationDetailsTypeI createCouponInformationDetailsTypeI() {
        return new CouponInformationDetailsTypeI();
    }

    /**
     * Create an instance of {@link FormOfPaymentDetailsType213594C }
     * 
     */
    public FormOfPaymentDetailsType213594C createFormOfPaymentDetailsType213594C() {
        return new FormOfPaymentDetailsType213594C();
    }

    /**
     * Create an instance of {@link ProductDetailsType }
     * 
     */
    public ProductDetailsType createProductDetailsType() {
        return new ProductDetailsType();
    }

    /**
     * Create an instance of {@link RoutingInfoGroupType }
     * 
     */
    public RoutingInfoGroupType createRoutingInfoGroupType() {
        return new RoutingInfoGroupType();
    }

    /**
     * Create an instance of {@link CompanyIdentificationTypeI }
     * 
     */
    public CompanyIdentificationTypeI createCompanyIdentificationTypeI() {
        return new CompanyIdentificationTypeI();
    }

    /**
     * Create an instance of {@link FareComponentsInfoType }
     * 
     */
    public FareComponentsInfoType createFareComponentsInfoType() {
        return new FareComponentsInfoType();
    }

    /**
     * Create an instance of {@link TravelProductInformationType }
     * 
     */
    public TravelProductInformationType createTravelProductInformationType() {
        return new TravelProductInformationType();
    }

    /**
     * Create an instance of {@link AssociatedChargesInformationType }
     * 
     */
    public AssociatedChargesInformationType createAssociatedChargesInformationType() {
        return new AssociatedChargesInformationType();
    }

    /**
     * Create an instance of {@link PassengerFaresInfoType }
     * 
     */
    public PassengerFaresInfoType createPassengerFaresInfoType() {
        return new PassengerFaresInfoType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link ProductDateTimeTypeI105646C }
     * 
     */
    public ProductDateTimeTypeI105646C createProductDateTimeTypeI105646C() {
        return new ProductDateTimeTypeI105646C();
    }

    /**
     * Create an instance of {@link DateAndTimeInformationTypeI67562S }
     * 
     */
    public DateAndTimeInformationTypeI67562S createDateAndTimeInformationTypeI67562S() {
        return new DateAndTimeInformationTypeI67562S();
    }

    /**
     * Create an instance of {@link SpecialRequirementsDetailsType }
     * 
     */
    public SpecialRequirementsDetailsType createSpecialRequirementsDetailsType() {
        return new SpecialRequirementsDetailsType();
    }

    /**
     * Create an instance of {@link ServiceRequestDetailsType }
     * 
     */
    public ServiceRequestDetailsType createServiceRequestDetailsType() {
        return new ServiceRequestDetailsType();
    }

    /**
     * Create an instance of {@link NumberOfUnitsType }
     * 
     */
    public NumberOfUnitsType createNumberOfUnitsType() {
        return new NumberOfUnitsType();
    }

    /**
     * Create an instance of {@link FeeOptionsType }
     * 
     */
    public FeeOptionsType createFeeOptionsType() {
        return new FeeOptionsType();
    }

    /**
     * Create an instance of {@link FareDetailsTypeI }
     * 
     */
    public FareDetailsTypeI createFareDetailsTypeI() {
        return new FareDetailsTypeI();
    }

    /**
     * Create an instance of {@link BookingClassInfoType86938G }
     * 
     */
    public BookingClassInfoType86938G createBookingClassInfoType86938G() {
        return new BookingClassInfoType86938G();
    }

    /**
     * Create an instance of {@link GenericDetailsTypeI }
     * 
     */
    public GenericDetailsTypeI createGenericDetailsTypeI() {
        return new GenericDetailsTypeI();
    }

    /**
     * Create an instance of {@link CouponInformationTypeI }
     * 
     */
    public CouponInformationTypeI createCouponInformationTypeI() {
        return new CouponInformationTypeI();
    }

    /**
     * Create an instance of {@link DiscountAndPenaltyInformationType }
     * 
     */
    public DiscountAndPenaltyInformationType createDiscountAndPenaltyInformationType() {
        return new DiscountAndPenaltyInformationType();
    }

    /**
     * Create an instance of {@link TravellerTimeDetailsTypeI }
     * 
     */
    public TravellerTimeDetailsTypeI createTravellerTimeDetailsTypeI() {
        return new TravellerTimeDetailsTypeI();
    }

    /**
     * Create an instance of {@link TravelProductInformationType67536S }
     * 
     */
    public TravelProductInformationType67536S createTravelProductInformationType67536S() {
        return new TravelProductInformationType67536S();
    }

    /**
     * Create an instance of {@link TicketNumberDetailsTypeI }
     * 
     */
    public TicketNumberDetailsTypeI createTicketNumberDetailsTypeI() {
        return new TicketNumberDetailsTypeI();
    }

    /**
     * Create an instance of {@link PricingTicketingDetailsType67548S }
     * 
     */
    public PricingTicketingDetailsType67548S createPricingTicketingDetailsType67548S() {
        return new PricingTicketingDetailsType67548S();
    }

    /**
     * Create an instance of {@link OriginatorDetailsTypeI }
     * 
     */
    public OriginatorDetailsTypeI createOriginatorDetailsTypeI() {
        return new OriginatorDetailsTypeI();
    }

    /**
     * Create an instance of {@link SpecialRequirementsTypeDetailsType105615C }
     * 
     */
    public SpecialRequirementsTypeDetailsType105615C createSpecialRequirementsTypeDetailsType105615C() {
        return new SpecialRequirementsTypeDetailsType105615C();
    }

    /**
     * Create an instance of {@link MonetaryInformationType }
     * 
     */
    public MonetaryInformationType createMonetaryInformationType() {
        return new MonetaryInformationType();
    }

    /**
     * Create an instance of {@link ProductDateTimeType }
     * 
     */
    public ProductDateTimeType createProductDateTimeType() {
        return new ProductDateTimeType();
    }

    /**
     * Create an instance of {@link ProductTypeDetailsTypeI }
     * 
     */
    public ProductTypeDetailsTypeI createProductTypeDetailsTypeI() {
        return new ProductTypeDetailsTypeI();
    }

    /**
     * Create an instance of {@link BinaryDataType }
     * 
     */
    public BinaryDataType createBinaryDataType() {
        return new BinaryDataType();
    }

    /**
     * Create an instance of {@link OriginAndDestinationDetailsTypeI }
     * 
     */
    public OriginAndDestinationDetailsTypeI createOriginAndDestinationDetailsTypeI() {
        return new OriginAndDestinationDetailsTypeI();
    }

    /**
     * Create an instance of {@link ConversionRateDetailsType }
     * 
     */
    public ConversionRateDetailsType createConversionRateDetailsType() {
        return new ConversionRateDetailsType();
    }

    /**
     * Create an instance of {@link TaxDetailsType105651C }
     * 
     */
    public TaxDetailsType105651C createTaxDetailsType105651C() {
        return new TaxDetailsType105651C();
    }

    /**
     * Create an instance of {@link FareQualifierDetailsType }
     * 
     */
    public FareQualifierDetailsType createFareQualifierDetailsType() {
        return new FareQualifierDetailsType();
    }

    /**
     * Create an instance of {@link ProcessingInformationType }
     * 
     */
    public ProcessingInformationType createProcessingInformationType() {
        return new ProcessingInformationType();
    }

    /**
     * Create an instance of {@link ProductDateTimeType105617C }
     * 
     */
    public ProductDateTimeType105617C createProductDateTimeType105617C() {
        return new ProductDateTimeType105617C();
    }

    /**
     * Create an instance of {@link SelectionDetailsInformationType105599C }
     * 
     */
    public SelectionDetailsInformationType105599C createSelectionDetailsInformationType105599C() {
        return new SelectionDetailsInformationType105599C();
    }

    /**
     * Create an instance of {@link CorporateFareIdentifiersType }
     * 
     */
    public CorporateFareIdentifiersType createCorporateFareIdentifiersType() {
        return new CorporateFareIdentifiersType();
    }

    /**
     * Create an instance of {@link ReasonForChangeType }
     * 
     */
    public ReasonForChangeType createReasonForChangeType() {
        return new ReasonForChangeType();
    }

    /**
     * Create an instance of {@link TravellerInsuranceInformationType67570S }
     * 
     */
    public TravellerInsuranceInformationType67570S createTravellerInsuranceInformationType67570S() {
        return new TravellerInsuranceInformationType67570S();
    }

    /**
     * Create an instance of {@link FormOfPaymentType148309S }
     * 
     */
    public FormOfPaymentType148309S createFormOfPaymentType148309S() {
        return new FormOfPaymentType148309S();
    }

    /**
     * Create an instance of {@link CompanyIdentificationType }
     * 
     */
    public CompanyIdentificationType createCompanyIdentificationType() {
        return new CompanyIdentificationType();
    }

    /**
     * Create an instance of {@link FareDetailsTypeI105570C }
     * 
     */
    public FareDetailsTypeI105570C createFareDetailsTypeI105570C() {
        return new FareDetailsTypeI105570C();
    }

    /**
     * Create an instance of {@link TariffInformationType }
     * 
     */
    public TariffInformationType createTariffInformationType() {
        return new TariffInformationType();
    }

    /**
     * Create an instance of {@link AllFaresInfoType }
     * 
     */
    public AllFaresInfoType createAllFaresInfoType() {
        return new AllFaresInfoType();
    }

    /**
     * Create an instance of {@link BaggageDetailsType }
     * 
     */
    public BaggageDetailsType createBaggageDetailsType() {
        return new BaggageDetailsType();
    }

    /**
     * Create an instance of {@link FareRulesInformationTypeI }
     * 
     */
    public FareRulesInformationTypeI createFareRulesInformationTypeI() {
        return new FareRulesInformationTypeI();
    }

    /**
     * Create an instance of {@link TravellerSurnameInformationTypeI }
     * 
     */
    public TravellerSurnameInformationTypeI createTravellerSurnameInformationTypeI() {
        return new TravellerSurnameInformationTypeI();
    }

    /**
     * Create an instance of {@link AdditionalProductTypeI }
     * 
     */
    public AdditionalProductTypeI createAdditionalProductTypeI() {
        return new AdditionalProductTypeI();
    }

    /**
     * Create an instance of {@link TicketingPriceSchemeType }
     * 
     */
    public TicketingPriceSchemeType createTicketingPriceSchemeType() {
        return new TicketingPriceSchemeType();
    }

    /**
     * Create an instance of {@link RateTariffClassInformationTypeI }
     * 
     */
    public RateTariffClassInformationTypeI createRateTariffClassInformationTypeI() {
        return new RateTariffClassInformationTypeI();
    }

    /**
     * Create an instance of {@link FareQualifierDetailsType67539S }
     * 
     */
    public FareQualifierDetailsType67539S createFareQualifierDetailsType67539S() {
        return new FareQualifierDetailsType67539S();
    }

    /**
     * Create an instance of {@link ProductTypeDetailsType105567C }
     * 
     */
    public ProductTypeDetailsType105567C createProductTypeDetailsType105567C() {
        return new ProductTypeDetailsType105567C();
    }

    /**
     * Create an instance of {@link SeatRequestParametersType }
     * 
     */
    public SeatRequestParametersType createSeatRequestParametersType() {
        return new SeatRequestParametersType();
    }

    /**
     * Create an instance of {@link DateAndTimeInformationTypeI }
     * 
     */
    public DateAndTimeInformationTypeI createDateAndTimeInformationTypeI() {
        return new DateAndTimeInformationTypeI();
    }

    /**
     * Create an instance of {@link DateAndTimeInformationType }
     * 
     */
    public DateAndTimeInformationType createDateAndTimeInformationType() {
        return new DateAndTimeInformationType();
    }

    /**
     * Create an instance of {@link CorporateFareInformationType }
     * 
     */
    public CorporateFareInformationType createCorporateFareInformationType() {
        return new CorporateFareInformationType();
    }

    /**
     * Create an instance of {@link PricingTicketingSubsequentTypeI67532S }
     * 
     */
    public PricingTicketingSubsequentTypeI67532S createPricingTicketingSubsequentTypeI67532S() {
        return new PricingTicketingSubsequentTypeI67532S();
    }

    /**
     * Create an instance of {@link FrequentTravellerIdentificationType }
     * 
     */
    public FrequentTravellerIdentificationType createFrequentTravellerIdentificationType() {
        return new FrequentTravellerIdentificationType();
    }

    /**
     * Create an instance of {@link FareCategoryCodesTypeI }
     * 
     */
    public FareCategoryCodesTypeI createFareCategoryCodesTypeI() {
        return new FareCategoryCodesTypeI();
    }

    /**
     * Create an instance of {@link BookingClassInfoType }
     * 
     */
    public BookingClassInfoType createBookingClassInfoType() {
        return new BookingClassInfoType();
    }

    /**
     * Create an instance of {@link FrequentTravellerIdentificationType190677C }
     * 
     */
    public FrequentTravellerIdentificationType190677C createFrequentTravellerIdentificationType190677C() {
        return new FrequentTravellerIdentificationType190677C();
    }

    /**
     * Create an instance of {@link ConversionRateDetailsTypeI }
     * 
     */
    public ConversionRateDetailsTypeI createConversionRateDetailsTypeI() {
        return new ConversionRateDetailsTypeI();
    }

    /**
     * Create an instance of {@link StatusDetailsType }
     * 
     */
    public StatusDetailsType createStatusDetailsType() {
        return new StatusDetailsType();
    }

    /**
     * Create an instance of {@link TaxDetailsType67573S }
     * 
     */
    public TaxDetailsType67573S createTaxDetailsType67573S() {
        return new TaxDetailsType67573S();
    }

    /**
     * Create an instance of {@link ReferencingDetailsType }
     * 
     */
    public ReferencingDetailsType createReferencingDetailsType() {
        return new ReferencingDetailsType();
    }

    /**
     * Create an instance of {@link BagtagDetailsTypeI }
     * 
     */
    public BagtagDetailsTypeI createBagtagDetailsTypeI() {
        return new BagtagDetailsTypeI();
    }

    /**
     * Create an instance of {@link SpecificTravellerDetailsTypeI }
     * 
     */
    public SpecificTravellerDetailsTypeI createSpecificTravellerDetailsTypeI() {
        return new SpecificTravellerDetailsTypeI();
    }

    /**
     * Create an instance of {@link PricingTicketingSubsequentTypeI }
     * 
     */
    public PricingTicketingSubsequentTypeI createPricingTicketingSubsequentTypeI() {
        return new PricingTicketingSubsequentTypeI();
    }

    /**
     * Create an instance of {@link GenericDetailsType }
     * 
     */
    public GenericDetailsType createGenericDetailsType() {
        return new GenericDetailsType();
    }

    /**
     * Create an instance of {@link MonetaryInformationType67503S }
     * 
     */
    public MonetaryInformationType67503S createMonetaryInformationType67503S() {
        return new MonetaryInformationType67503S();
    }

    /**
     * Create an instance of {@link SelectionDetailsInformationType }
     * 
     */
    public SelectionDetailsInformationType createSelectionDetailsInformationType() {
        return new SelectionDetailsInformationType();
    }

    /**
     * Create an instance of {@link MonetaryInformationDetailsType }
     * 
     */
    public MonetaryInformationDetailsType createMonetaryInformationDetailsType() {
        return new MonetaryInformationDetailsType();
    }

    /**
     * Create an instance of {@link PassengerInfoType }
     * 
     */
    public PassengerInfoType createPassengerInfoType() {
        return new PassengerInfoType();
    }

    /**
     * Create an instance of {@link ServiceRequestType }
     * 
     */
    public ServiceRequestType createServiceRequestType() {
        return new ServiceRequestType();
    }

    /**
     * Create an instance of {@link SpecialRequirementsDataDetailsTypeI }
     * 
     */
    public SpecialRequirementsDataDetailsTypeI createSpecialRequirementsDataDetailsTypeI() {
        return new SpecialRequirementsDataDetailsTypeI();
    }

    /**
     * Create an instance of {@link ProductDetailsType105565C }
     * 
     */
    public ProductDetailsType105565C createProductDetailsType105565C() {
        return new ProductDetailsType105565C();
    }

    /**
     * Create an instance of {@link NumberOfUnitsTypeI }
     * 
     */
    public NumberOfUnitsTypeI createNumberOfUnitsTypeI() {
        return new NumberOfUnitsTypeI();
    }

    /**
     * Create an instance of {@link MonetaryInformationDetailsType105604C }
     * 
     */
    public MonetaryInformationDetailsType105604C createMonetaryInformationDetailsType105604C() {
        return new MonetaryInformationDetailsType105604C();
    }

    /**
     * Create an instance of {@link SpecialRequirementsTypeDetailsType105612C }
     * 
     */
    public SpecialRequirementsTypeDetailsType105612C createSpecialRequirementsTypeDetailsType105612C() {
        return new SpecialRequirementsTypeDetailsType105612C();
    }

    /**
     * Create an instance of {@link ReferenceInfoType }
     * 
     */
    public ReferenceInfoType createReferenceInfoType() {
        return new ReferenceInfoType();
    }

    /**
     * Create an instance of {@link DummySegmentTypeI }
     * 
     */
    public DummySegmentTypeI createDummySegmentTypeI() {
        return new DummySegmentTypeI();
    }

    /**
     * Create an instance of {@link ServicePriceServiceViaCatalogue }
     * 
     */
    public ServicePriceServiceViaCatalogue createServicePriceServiceViaCatalogue() {
        return new ServicePriceServiceViaCatalogue();
    }

    /**
     * Create an instance of {@link SpecialRequirementsDetailsType67545S }
     * 
     */
    public SpecialRequirementsDetailsType67545S createSpecialRequirementsDetailsType67545S() {
        return new SpecialRequirementsDetailsType67545S();
    }

    /**
     * Create an instance of {@link TicketNumberType }
     * 
     */
    public TicketNumberType createTicketNumberType() {
        return new TicketNumberType();
    }

    /**
     * Create an instance of {@link FeeOptionInfoType }
     * 
     */
    public FeeOptionInfoType createFeeOptionInfoType() {
        return new FeeOptionInfoType();
    }

    /**
     * Create an instance of {@link SpecificDataInformationType }
     * 
     */
    public SpecificDataInformationType createSpecificDataInformationType() {
        return new SpecificDataInformationType();
    }

    /**
     * Create an instance of {@link ItemNumberType }
     * 
     */
    public ItemNumberType createItemNumberType() {
        return new ItemNumberType();
    }

    /**
     * Create an instance of {@link TourDetailsTypeI }
     * 
     */
    public TourDetailsTypeI createTourDetailsTypeI() {
        return new TourDetailsTypeI();
    }

    /**
     * Create an instance of {@link TravellerInsuranceInformationType }
     * 
     */
    public TravellerInsuranceInformationType createTravellerInsuranceInformationType() {
        return new TravellerInsuranceInformationType();
    }

    /**
     * Create an instance of {@link FormOfPaymentType }
     * 
     */
    public FormOfPaymentType createFormOfPaymentType() {
        return new FormOfPaymentType();
    }

    /**
     * Create an instance of {@link PricingOptionType }
     * 
     */
    public PricingOptionType createPricingOptionType() {
        return new PricingOptionType();
    }

    /**
     * Create an instance of {@link DiscountPenaltyMonetaryInformationTypeI }
     * 
     */
    public DiscountPenaltyMonetaryInformationTypeI createDiscountPenaltyMonetaryInformationTypeI() {
        return new DiscountPenaltyMonetaryInformationTypeI();
    }

    /**
     * Create an instance of {@link MileageTimeDetailsTypeI }
     * 
     */
    public MileageTimeDetailsTypeI createMileageTimeDetailsTypeI() {
        return new MileageTimeDetailsTypeI();
    }

    /**
     * Create an instance of {@link PricingTicketingDetailsType }
     * 
     */
    public PricingTicketingDetailsType createPricingTicketingDetailsType() {
        return new PricingTicketingDetailsType();
    }

    /**
     * Create an instance of {@link PassengerServiceRequestType }
     * 
     */
    public PassengerServiceRequestType createPassengerServiceRequestType() {
        return new PassengerServiceRequestType();
    }

    /**
     * Create an instance of {@link MonetaryInformationDetailsTypeI }
     * 
     */
    public MonetaryInformationDetailsTypeI createMonetaryInformationDetailsTypeI() {
        return new MonetaryInformationDetailsTypeI();
    }

    /**
     * Create an instance of {@link QuantityDetailsTypeI }
     * 
     */
    public QuantityDetailsTypeI createQuantityDetailsTypeI() {
        return new QuantityDetailsTypeI();
    }

    /**
     * Create an instance of {@link DateAndTimeDetailsTypeI }
     * 
     */
    public DateAndTimeDetailsTypeI createDateAndTimeDetailsTypeI() {
        return new DateAndTimeDetailsTypeI();
    }

    /**
     * Create an instance of {@link PricingOrTicketingSubsequentType }
     * 
     */
    public PricingOrTicketingSubsequentType createPricingOrTicketingSubsequentType() {
        return new PricingOrTicketingSubsequentType();
    }

    /**
     * Create an instance of {@link InteractiveFreeTextType }
     * 
     */
    public InteractiveFreeTextType createInteractiveFreeTextType() {
        return new InteractiveFreeTextType();
    }

    /**
     * Create an instance of {@link ProductLocationDetailsTypeI }
     * 
     */
    public ProductLocationDetailsTypeI createProductLocationDetailsTypeI() {
        return new ProductLocationDetailsTypeI();
    }

    /**
     * Create an instance of {@link IssueOriginatorType }
     * 
     */
    public IssueOriginatorType createIssueOriginatorType() {
        return new IssueOriginatorType();
    }

    /**
     * Create an instance of {@link ProductFacilitiesTypeI }
     * 
     */
    public ProductFacilitiesTypeI createProductFacilitiesTypeI() {
        return new ProductFacilitiesTypeI();
    }

    /**
     * Create an instance of {@link DataTypeInformationType159331C }
     * 
     */
    public DataTypeInformationType159331C createDataTypeInformationType159331C() {
        return new DataTypeInformationType159331C();
    }

    /**
     * Create an instance of {@link AdditionalPriceInformationType }
     * 
     */
    public AdditionalPriceInformationType createAdditionalPriceInformationType() {
        return new AdditionalPriceInformationType();
    }

    /**
     * Create an instance of {@link RelatedProductInformationTypeI }
     * 
     */
    public RelatedProductInformationTypeI createRelatedProductInformationTypeI() {
        return new RelatedProductInformationTypeI();
    }

    /**
     * Create an instance of {@link AdditionalProductDetailsTypeI }
     * 
     */
    public AdditionalProductDetailsTypeI createAdditionalProductDetailsTypeI() {
        return new AdditionalProductDetailsTypeI();
    }

    /**
     * Create an instance of {@link OriginatorOfRequestDetailsTypeI }
     * 
     */
    public OriginatorOfRequestDetailsTypeI createOriginatorOfRequestDetailsTypeI() {
        return new OriginatorOfRequestDetailsTypeI();
    }

    /**
     * Create an instance of {@link ProductIdentificationDetailsType }
     * 
     */
    public ProductIdentificationDetailsType createProductIdentificationDetailsType() {
        return new ProductIdentificationDetailsType();
    }

    /**
     * Create an instance of {@link QuantityTypeI }
     * 
     */
    public QuantityTypeI createQuantityTypeI() {
        return new QuantityTypeI();
    }

    /**
     * Create an instance of {@link FareCalculationCodeDetailsType }
     * 
     */
    public FareCalculationCodeDetailsType createFareCalculationCodeDetailsType() {
        return new FareCalculationCodeDetailsType();
    }

    /**
     * Create an instance of {@link SpecialRequirementsDataDetailsType }
     * 
     */
    public SpecialRequirementsDataDetailsType createSpecialRequirementsDataDetailsType() {
        return new SpecialRequirementsDataDetailsType();
    }

    /**
     * Create an instance of {@link OriginatorInfoType }
     * 
     */
    public OriginatorInfoType createOriginatorInfoType() {
        return new OriginatorInfoType();
    }

    /**
     * Create an instance of {@link SegmentPricingInfoType }
     * 
     */
    public SegmentPricingInfoType createSegmentPricingInfoType() {
        return new SegmentPricingInfoType();
    }

    /**
     * Create an instance of {@link TaxType }
     * 
     */
    public TaxType createTaxType() {
        return new TaxType();
    }

    /**
     * Create an instance of {@link SubItineraryDetailsType }
     * 
     */
    public SubItineraryDetailsType createSubItineraryDetailsType() {
        return new SubItineraryDetailsType();
    }

    /**
     * Create an instance of {@link ProductIdentificationDetailsType105594C }
     * 
     */
    public ProductIdentificationDetailsType105594C createProductIdentificationDetailsType105594C() {
        return new ProductIdentificationDetailsType105594C();
    }

    /**
     * Create an instance of {@link FormOfPaymentDetailsType }
     * 
     */
    public FormOfPaymentDetailsType createFormOfPaymentDetailsType() {
        return new FormOfPaymentDetailsType();
    }

    /**
     * Create an instance of {@link FareInformationType }
     * 
     */
    public FareInformationType createFareInformationType() {
        return new FareInformationType();
    }

    /**
     * Create an instance of {@link SegmentRepetitionControlType }
     * 
     */
    public SegmentRepetitionControlType createSegmentRepetitionControlType() {
        return new SegmentRepetitionControlType();
    }

    /**
     * Create an instance of {@link TravellerInformationTypeI }
     * 
     */
    public TravellerInformationTypeI createTravellerInformationTypeI() {
        return new TravellerInformationTypeI();
    }

    /**
     * Create an instance of {@link TaxDetailsType105578C }
     * 
     */
    public TaxDetailsType105578C createTaxDetailsType105578C() {
        return new TaxDetailsType105578C();
    }

    /**
     * Create an instance of {@link ProductIdentificationDetailsTypeI }
     * 
     */
    public ProductIdentificationDetailsTypeI createProductIdentificationDetailsTypeI() {
        return new ProductIdentificationDetailsTypeI();
    }

    /**
     * Create an instance of {@link FreeTextQualificationType }
     * 
     */
    public FreeTextQualificationType createFreeTextQualificationType() {
        return new FreeTextQualificationType();
    }

    /**
     * Create an instance of {@link PrincingByFareBasisType }
     * 
     */
    public PrincingByFareBasisType createPrincingByFareBasisType() {
        return new PrincingByFareBasisType();
    }

    /**
     * Create an instance of {@link DateAndTimeDetailsType }
     * 
     */
    public DateAndTimeDetailsType createDateAndTimeDetailsType() {
        return new DateAndTimeDetailsType();
    }

    /**
     * Create an instance of {@link RoutingInformationTypeI }
     * 
     */
    public RoutingInformationTypeI createRoutingInformationTypeI() {
        return new RoutingInformationTypeI();
    }

    /**
     * Create an instance of {@link FeeDetailsInfoType }
     * 
     */
    public FeeDetailsInfoType createFeeDetailsInfoType() {
        return new FeeDetailsInfoType();
    }

    /**
     * Create an instance of {@link RateTariffClassInformationTypeI105552C }
     * 
     */
    public RateTariffClassInformationTypeI105552C createRateTariffClassInformationTypeI105552C() {
        return new RateTariffClassInformationTypeI105552C();
    }

    /**
     * Create an instance of {@link NumberOfUnitDetailsType }
     * 
     */
    public NumberOfUnitDetailsType createNumberOfUnitDetailsType() {
        return new NumberOfUnitDetailsType();
    }

    /**
     * Create an instance of {@link ProductDateTimeTypeI }
     * 
     */
    public ProductDateTimeTypeI createProductDateTimeTypeI() {
        return new ProductDateTimeTypeI();
    }

    /**
     * Create an instance of {@link PricingUnitInfoType }
     * 
     */
    public PricingUnitInfoType createPricingUnitInfoType() {
        return new PricingUnitInfoType();
    }

    /**
     * Create an instance of {@link SelectionDetailsType67537S }
     * 
     */
    public SelectionDetailsType67537S createSelectionDetailsType67537S() {
        return new SelectionDetailsType67537S();
    }

    /**
     * Create an instance of {@link FareComponentInfoType }
     * 
     */
    public FareComponentInfoType createFareComponentInfoType() {
        return new FareComponentInfoType();
    }

    /**
     * Create an instance of {@link AttributeInformationType }
     * 
     */
    public AttributeInformationType createAttributeInformationType() {
        return new AttributeInformationType();
    }

    /**
     * Create an instance of {@link SegmentRepetitionControlDetailsType }
     * 
     */
    public SegmentRepetitionControlDetailsType createSegmentRepetitionControlDetailsType() {
        return new SegmentRepetitionControlDetailsType();
    }

    /**
     * Create an instance of {@link RangeOfRowsDetailsTypeI }
     * 
     */
    public RangeOfRowsDetailsTypeI createRangeOfRowsDetailsTypeI() {
        return new RangeOfRowsDetailsTypeI();
    }

    /**
     * Create an instance of {@link TourInformationType }
     * 
     */
    public TourInformationType createTourInformationType() {
        return new TourInformationType();
    }

    /**
     * Create an instance of {@link FareTypeGroupingInformationTypeI }
     * 
     */
    public FareTypeGroupingInformationTypeI createFareTypeGroupingInformationTypeI() {
        return new FareTypeGroupingInformationTypeI();
    }

    /**
     * Create an instance of {@link OriginatorIdentificationDetailsTypeI }
     * 
     */
    public OriginatorIdentificationDetailsTypeI createOriginatorIdentificationDetailsTypeI() {
        return new OriginatorIdentificationDetailsTypeI();
    }

    /**
     * Create an instance of {@link FrequentFlyerInfoType }
     * 
     */
    public FrequentFlyerInfoType createFrequentFlyerInfoType() {
        return new FrequentFlyerInfoType();
    }

    /**
     * Create an instance of {@link NumberOfUnitDetailsTypeI }
     * 
     */
    public NumberOfUnitDetailsTypeI createNumberOfUnitDetailsTypeI() {
        return new NumberOfUnitDetailsTypeI();
    }

    /**
     * Create an instance of {@link ReissueRefundType }
     * 
     */
    public ReissueRefundType createReissueRefundType() {
        return new ReissueRefundType();
    }

    /**
     * Create an instance of {@link FeeBreakdownType }
     * 
     */
    public FeeBreakdownType createFeeBreakdownType() {
        return new FeeBreakdownType();
    }

    /**
     * Create an instance of {@link ProductTypeDetailsType105595C }
     * 
     */
    public ProductTypeDetailsType105595C createProductTypeDetailsType105595C() {
        return new ProductTypeDetailsType105595C();
    }

    /**
     * Create an instance of {@link SelectionDetailsType }
     * 
     */
    public SelectionDetailsType createSelectionDetailsType() {
        return new SelectionDetailsType();
    }

    /**
     * Create an instance of {@link SpecialRequirementsTypeDetailsType }
     * 
     */
    public SpecialRequirementsTypeDetailsType createSpecialRequirementsTypeDetailsType() {
        return new SpecialRequirementsTypeDetailsType();
    }

    /**
     * Create an instance of {@link TaxDetailsTypeI }
     * 
     */
    public TaxDetailsTypeI createTaxDetailsTypeI() {
        return new TaxDetailsTypeI();
    }

    /**
     * Create an instance of {@link DiscountPenaltyInformationType }
     * 
     */
    public DiscountPenaltyInformationType createDiscountPenaltyInformationType() {
        return new DiscountPenaltyInformationType();
    }

    /**
     * Create an instance of {@link FareComponentInformationTypeI }
     * 
     */
    public FareComponentInformationTypeI createFareComponentInformationTypeI() {
        return new FareComponentInformationTypeI();
    }

    /**
     * Create an instance of {@link SpecialRequirementsDetailsType67547S }
     * 
     */
    public SpecialRequirementsDetailsType67547S createSpecialRequirementsDetailsType67547S() {
        return new SpecialRequirementsDetailsType67547S();
    }

    /**
     * Create an instance of {@link MarriageControlDetailsTypeI }
     * 
     */
    public MarriageControlDetailsTypeI createMarriageControlDetailsTypeI() {
        return new MarriageControlDetailsTypeI();
    }

    /**
     * Create an instance of {@link ProductTypeDetailsType }
     * 
     */
    public ProductTypeDetailsType createProductTypeDetailsType() {
        return new ProductTypeDetailsType();
    }

    /**
     * Create an instance of {@link SpecificTravellerTypeI }
     * 
     */
    public SpecificTravellerTypeI createSpecificTravellerTypeI() {
        return new SpecificTravellerTypeI();
    }

    /**
     * Create an instance of {@link TaxOptionsInfoType }
     * 
     */
    public TaxOptionsInfoType createTaxOptionsInfoType() {
        return new TaxOptionsInfoType();
    }

    /**
     * Create an instance of {@link FlightInformationType }
     * 
     */
    public FlightInformationType createFlightInformationType() {
        return new FlightInformationType();
    }

    /**
     * Create an instance of {@link PassengerDetailsType }
     * 
     */
    public PassengerDetailsType createPassengerDetailsType() {
        return new PassengerDetailsType();
    }

    /**
     * Create an instance of {@link SeatRequestParametersTypeI }
     * 
     */
    public SeatRequestParametersTypeI createSeatRequestParametersTypeI() {
        return new SeatRequestParametersTypeI();
    }

    /**
     * Create an instance of {@link PassengerTypeInfoType }
     * 
     */
    public PassengerTypeInfoType createPassengerTypeInfoType() {
        return new PassengerTypeInfoType();
    }

    /**
     * Create an instance of {@link DataTypeInformationType }
     * 
     */
    public DataTypeInformationType createDataTypeInformationType() {
        return new DataTypeInformationType();
    }

    /**
     * Create an instance of {@link LocationDetailsTypeI }
     * 
     */
    public LocationDetailsTypeI createLocationDetailsTypeI() {
        return new LocationDetailsTypeI();
    }

    /**
     * Create an instance of {@link FlightInfoType }
     * 
     */
    public FlightInfoType createFlightInfoType() {
        return new FlightInfoType();
    }

    /**
     * Create an instance of {@link ConversionRateType67496S }
     * 
     */
    public ConversionRateType67496S createConversionRateType67496S() {
        return new ConversionRateType67496S();
    }

    /**
     * Create an instance of {@link FrequentTravellerIdentificationCodeType }
     * 
     */
    public FrequentTravellerIdentificationCodeType createFrequentTravellerIdentificationCodeType() {
        return new FrequentTravellerIdentificationCodeType();
    }

    /**
     * Create an instance of {@link TravellerDetailsTypeI }
     * 
     */
    public TravellerDetailsTypeI createTravellerDetailsTypeI() {
        return new TravellerDetailsTypeI();
    }

    /**
     * Create an instance of {@link FeeDetailsInfoType168126G }
     * 
     */
    public FeeDetailsInfoType168126G createFeeDetailsInfoType168126G() {
        return new FeeDetailsInfoType168126G();
    }

    /**
     * Create an instance of {@link PassengerFlightInfoType }
     * 
     */
    public PassengerFlightInfoType createPassengerFlightInfoType() {
        return new PassengerFlightInfoType();
    }

}
