//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.05 at 06:47:52 ���� KST 
//


package com.koreanair.common_external.altea.vo.fop_updateformofpayment_12_1_1a;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.koreanair.common_external.altea.vo.fop_updateformofpayment_12_1_1a package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.koreanair.common_external.altea.vo.fop_updateformofpayment_12_1_1a
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SequenceDetailsTypeU }
     * 
     */
    public SequenceDetailsTypeU createSequenceDetailsTypeU() {
        return new SequenceDetailsTypeU();
    }

    /**
     * Create an instance of {@link ErrorGroupType }
     * 
     */
    public ErrorGroupType createErrorGroupType() {
        return new ErrorGroupType();
    }

    /**
     * Create an instance of {@link AuthorizationApprovalDataType }
     * 
     */
    public AuthorizationApprovalDataType createAuthorizationApprovalDataType() {
        return new AuthorizationApprovalDataType();
    }

    /**
     * Create an instance of {@link CompanyInformationType }
     * 
     */
    public CompanyInformationType createCompanyInformationType() {
        return new CompanyInformationType();
    }

    /**
     * Create an instance of {@link StructuredDateTimeType190041C }
     * 
     */
    public StructuredDateTimeType190041C createStructuredDateTimeType190041C() {
        return new StructuredDateTimeType190041C();
    }

    /**
     * Create an instance of {@link StructuredDateTimeType190049C }
     * 
     */
    public StructuredDateTimeType190049C createStructuredDateTimeType190049C() {
        return new StructuredDateTimeType190049C();
    }

    /**
     * Create an instance of {@link MonetaryInformationDetailsTypeI }
     * 
     */
    public MonetaryInformationDetailsTypeI createMonetaryInformationDetailsTypeI() {
        return new MonetaryInformationDetailsTypeI();
    }

    /**
     * Create an instance of {@link ReferencingDetailsTypeI }
     * 
     */
    public ReferencingDetailsTypeI createReferencingDetailsTypeI() {
        return new ReferencingDetailsTypeI();
    }

    /**
     * Create an instance of {@link GenericAuthorisationResultType68631S }
     * 
     */
    public GenericAuthorisationResultType68631S createGenericAuthorisationResultType68631S() {
        return new GenericAuthorisationResultType68631S();
    }

    /**
     * Create an instance of {@link ThreeDomainSecureGroupType.TdsBlobData }
     * 
     */
    public ThreeDomainSecureGroupType.TdsBlobData createThreeDomainSecureGroupTypeTdsBlobData() {
        return new ThreeDomainSecureGroupType.TdsBlobData();
    }

    /**
     * Create an instance of {@link SequenceInformationTypeU }
     * 
     */
    public SequenceInformationTypeU createSequenceInformationTypeU() {
        return new SequenceInformationTypeU();
    }

    /**
     * Create an instance of {@link ReferenceInfoType130752S }
     * 
     */
    public ReferenceInfoType130752S createReferenceInfoType130752S() {
        return new ReferenceInfoType130752S();
    }

    /**
     * Create an instance of {@link ReferencingDetailsType }
     * 
     */
    public ReferencingDetailsType createReferencingDetailsType() {
        return new ReferencingDetailsType();
    }

    /**
     * Create an instance of {@link MessageReferenceType }
     * 
     */
    public MessageReferenceType createMessageReferenceType() {
        return new MessageReferenceType();
    }

    /**
     * Create an instance of {@link PaymentGroupType }
     * 
     */
    public PaymentGroupType createPaymentGroupType() {
        return new PaymentGroupType();
    }

    /**
     * Create an instance of {@link FormOfPaymentDetailsTypeI }
     * 
     */
    public FormOfPaymentDetailsTypeI createFormOfPaymentDetailsTypeI() {
        return new FormOfPaymentDetailsTypeI();
    }

    /**
     * Create an instance of {@link DummySegmentTypeI }
     * 
     */
    public DummySegmentTypeI createDummySegmentTypeI() {
        return new DummySegmentTypeI();
    }

    /**
     * Create an instance of {@link FraudScreeningGroupType.SecurityCode }
     * 
     */
    public FraudScreeningGroupType.SecurityCode createFraudScreeningGroupTypeSecurityCode() {
        return new FraudScreeningGroupType.SecurityCode();
    }

    /**
     * Create an instance of {@link ReferencingDetailsTypeI190001C }
     * 
     */
    public ReferencingDetailsTypeI190001C createReferencingDetailsTypeI190001C() {
        return new ReferencingDetailsTypeI190001C();
    }

    /**
     * Create an instance of {@link ApplicationErrorInformationType }
     * 
     */
    public ApplicationErrorInformationType createApplicationErrorInformationType() {
        return new ApplicationErrorInformationType();
    }

    /**
     * Create an instance of {@link StructuredDateTimeInformationType130753S }
     * 
     */
    public StructuredDateTimeInformationType130753S createStructuredDateTimeInformationType130753S() {
        return new StructuredDateTimeInformationType130753S();
    }

    /**
     * Create an instance of {@link DetailedPaymentDataType }
     * 
     */
    public DetailedPaymentDataType createDetailedPaymentDataType() {
        return new DetailedPaymentDataType();
    }

    /**
     * Create an instance of {@link ElementManagementSegmentType }
     * 
     */
    public ElementManagementSegmentType createElementManagementSegmentType() {
        return new ElementManagementSegmentType();
    }

    /**
     * Create an instance of {@link InvoiceValidationGroupType }
     * 
     */
    public InvoiceValidationGroupType createInvoiceValidationGroupType() {
        return new InvoiceValidationGroupType();
    }

    /**
     * Create an instance of {@link CreditCardSecurityType }
     * 
     */
    public CreditCardSecurityType createCreditCardSecurityType() {
        return new CreditCardSecurityType();
    }

    /**
     * Create an instance of {@link CodedAttributeType }
     * 
     */
    public CodedAttributeType createCodedAttributeType() {
        return new CodedAttributeType();
    }

    /**
     * Create an instance of {@link FormOfPaymentType }
     * 
     */
    public FormOfPaymentType createFormOfPaymentType() {
        return new FormOfPaymentType();
    }

    /**
     * Create an instance of {@link BinaryDataType }
     * 
     */
    public BinaryDataType createBinaryDataType() {
        return new BinaryDataType();
    }

    /**
     * Create an instance of {@link SecurityScreeningType }
     * 
     */
    public SecurityScreeningType createSecurityScreeningType() {
        return new SecurityScreeningType();
    }

    /**
     * Create an instance of {@link FormOfPaymentTypeI130697S }
     * 
     */
    public FormOfPaymentTypeI130697S createFormOfPaymentTypeI130697S() {
        return new FormOfPaymentTypeI130697S();
    }

    /**
     * Create an instance of {@link AttributeType130700S }
     * 
     */
    public AttributeType130700S createAttributeType130700S() {
        return new AttributeType130700S();
    }

    /**
     * Create an instance of {@link CodedAttributeInformationType }
     * 
     */
    public CodedAttributeInformationType createCodedAttributeInformationType() {
        return new CodedAttributeInformationType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link PaymentDataGroupType }
     * 
     */
    public PaymentDataGroupType createPaymentDataGroupType() {
        return new PaymentDataGroupType();
    }

    /**
     * Create an instance of {@link CodedAttributeInformationType189969C }
     * 
     */
    public CodedAttributeInformationType189969C createCodedAttributeInformationType189969C() {
        return new CodedAttributeInformationType189969C();
    }

    /**
     * Create an instance of {@link TransactionInformationsType }
     * 
     */
    public TransactionInformationsType createTransactionInformationsType() {
        return new TransactionInformationsType();
    }

    /**
     * Create an instance of {@link AynchronousPaymentTypeGroupStatus }
     * 
     */
    public AynchronousPaymentTypeGroupStatus createAynchronousPaymentTypeGroupStatus() {
        return new AynchronousPaymentTypeGroupStatus();
    }

    /**
     * Create an instance of {@link ReferencingDetailsTypeI189963C }
     * 
     */
    public ReferencingDetailsTypeI189963C createReferencingDetailsTypeI189963C() {
        return new ReferencingDetailsTypeI189963C();
    }

    /**
     * Create an instance of {@link InvoiceFopGroupType }
     * 
     */
    public InvoiceFopGroupType createInvoiceFopGroupType() {
        return new InvoiceFopGroupType();
    }

    /**
     * Create an instance of {@link CreditCardInformationType }
     * 
     */
    public CreditCardInformationType createCreditCardInformationType() {
        return new CreditCardInformationType();
    }

    /**
     * Create an instance of {@link FraudScreeningGroupType }
     * 
     */
    public FraudScreeningGroupType createFraudScreeningGroupType() {
        return new FraudScreeningGroupType();
    }

    /**
     * Create an instance of {@link CodedAttributeType130681S }
     * 
     */
    public CodedAttributeType130681S createCodedAttributeType130681S() {
        return new CodedAttributeType130681S();
    }

    /**
     * Create an instance of {@link AuthenticationDataType }
     * 
     */
    public AuthenticationDataType createAuthenticationDataType() {
        return new AuthenticationDataType();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link CreditCardStatusGroupType }
     * 
     */
    public CreditCardStatusGroupType createCreditCardStatusGroupType() {
        return new CreditCardStatusGroupType();
    }

    /**
     * Create an instance of {@link AuthorizationApprovalDataType189989C }
     * 
     */
    public AuthorizationApprovalDataType189989C createAuthorizationApprovalDataType189989C() {
        return new AuthorizationApprovalDataType189989C();
    }

    /**
     * Create an instance of {@link FrequencyDetailsTypeU }
     * 
     */
    public FrequencyDetailsTypeU createFrequencyDetailsTypeU() {
        return new FrequencyDetailsTypeU();
    }

    /**
     * Create an instance of {@link MeanOfPaymentDataType }
     * 
     */
    public MeanOfPaymentDataType createMeanOfPaymentDataType() {
        return new MeanOfPaymentDataType();
    }

    /**
     * Create an instance of {@link SpecificVisaLinkCreditCardInformationType }
     * 
     */
    public SpecificVisaLinkCreditCardInformationType createSpecificVisaLinkCreditCardInformationType() {
        return new SpecificVisaLinkCreditCardInformationType();
    }

    /**
     * Create an instance of {@link AttributeInformationTypeU }
     * 
     */
    public AttributeInformationTypeU createAttributeInformationTypeU() {
        return new AttributeInformationTypeU();
    }

    /**
     * Create an instance of {@link CreditCardDataGroupType }
     * 
     */
    public CreditCardDataGroupType createCreditCardDataGroupType() {
        return new CreditCardDataGroupType();
    }

    /**
     * Create an instance of {@link TransactionInformationForTicketingType }
     * 
     */
    public TransactionInformationForTicketingType createTransactionInformationForTicketingType() {
        return new TransactionInformationForTicketingType();
    }

    /**
     * Create an instance of {@link FrequencyTypeU }
     * 
     */
    public FrequencyTypeU createFrequencyTypeU() {
        return new FrequencyTypeU();
    }

    /**
     * Create an instance of {@link TimeZoneIinformationType }
     * 
     */
    public TimeZoneIinformationType createTimeZoneIinformationType() {
        return new TimeZoneIinformationType();
    }

    /**
     * Create an instance of {@link ItemReferencesAndVersionsType }
     * 
     */
    public ItemReferencesAndVersionsType createItemReferencesAndVersionsType() {
        return new ItemReferencesAndVersionsType();
    }

    /**
     * Create an instance of {@link MonetaryInformationType }
     * 
     */
    public MonetaryInformationType createMonetaryInformationType() {
        return new MonetaryInformationType();
    }

    /**
     * Create an instance of {@link ReferenceInfoType130710S }
     * 
     */
    public ReferenceInfoType130710S createReferenceInfoType130710S() {
        return new ReferenceInfoType130710S();
    }

    /**
     * Create an instance of {@link ReferencingDetailsTypeI190048C }
     * 
     */
    public ReferencingDetailsTypeI190048C createReferencingDetailsTypeI190048C() {
        return new ReferencingDetailsTypeI190048C();
    }

    /**
     * Create an instance of {@link ReferenceInfoType }
     * 
     */
    public ReferenceInfoType createReferenceInfoType() {
        return new ReferenceInfoType();
    }

    /**
     * Create an instance of {@link FormOfPaymentDetailsType }
     * 
     */
    public FormOfPaymentDetailsType createFormOfPaymentDetailsType() {
        return new FormOfPaymentDetailsType();
    }

    /**
     * Create an instance of {@link ThreeDomainSecureGroupType }
     * 
     */
    public ThreeDomainSecureGroupType createThreeDomainSecureGroupType() {
        return new ThreeDomainSecureGroupType();
    }

    /**
     * Create an instance of {@link ReferenceInformationType }
     * 
     */
    public ReferenceInformationType createReferenceInformationType() {
        return new ReferenceInformationType();
    }

    /**
     * Create an instance of {@link StructuredDateTimeType }
     * 
     */
    public StructuredDateTimeType createStructuredDateTimeType() {
        return new StructuredDateTimeType();
    }

    /**
     * Create an instance of {@link FormOfPaymentDetailsTypeI189985C }
     * 
     */
    public FormOfPaymentDetailsTypeI189985C createFormOfPaymentDetailsTypeI189985C() {
        return new FormOfPaymentDetailsTypeI189985C();
    }

    /**
     * Create an instance of {@link StructuredDateTimeInformationType }
     * 
     */
    public StructuredDateTimeInformationType createStructuredDateTimeInformationType() {
        return new StructuredDateTimeInformationType();
    }

    /**
     * Create an instance of {@link FOPUpdateFormOfPayment.FopGroup.MopDescription }
     * 
     */
    public FOPUpdateFormOfPayment.FopGroup.MopDescription createFOPUpdateFormOfPaymentFopGroupMopDescription() {
        return new FOPUpdateFormOfPayment.FopGroup.MopDescription();
    }

    /**
     * Create an instance of {@link GenericAuthorisationResultType }
     * 
     */
    public GenericAuthorisationResultType createGenericAuthorisationResultType() {
        return new GenericAuthorisationResultType();
    }

    /**
     * Create an instance of {@link FOPUpdateFormOfPayment.FopGroup }
     * 
     */
    public FOPUpdateFormOfPayment.FopGroup createFOPUpdateFormOfPaymentFopGroup() {
        return new FOPUpdateFormOfPayment.FopGroup();
    }

    /**
     * Create an instance of {@link StructuredDateTimeInformationType130745S }
     * 
     */
    public StructuredDateTimeInformationType130745S createStructuredDateTimeInformationType130745S() {
        return new StructuredDateTimeInformationType130745S();
    }

    /**
     * Create an instance of {@link FormOfPaymentTypeI }
     * 
     */
    public FormOfPaymentTypeI createFormOfPaymentTypeI() {
        return new FormOfPaymentTypeI();
    }

    /**
     * Create an instance of {@link CreditCardDataType }
     * 
     */
    public CreditCardDataType createCreditCardDataType() {
        return new CreditCardDataType();
    }

    /**
     * Create an instance of {@link ResponseIdentificationType }
     * 
     */
    public ResponseIdentificationType createResponseIdentificationType() {
        return new ResponseIdentificationType();
    }

    /**
     * Create an instance of {@link FOPUpdateFormOfPayment }
     * 
     */
    public FOPUpdateFormOfPayment createFOPUpdateFormOfPayment() {
        return new FOPUpdateFormOfPayment();
    }

    /**
     * Create an instance of {@link ApplicationErrorDetailType }
     * 
     */
    public ApplicationErrorDetailType createApplicationErrorDetailType() {
        return new ApplicationErrorDetailType();
    }

    /**
     * Create an instance of {@link BinaryDataType130758S }
     * 
     */
    public BinaryDataType130758S createBinaryDataType130758S() {
        return new BinaryDataType130758S();
    }

}
