//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.10 at 06:01:13 ���� KST 
//


package com.koreanair.common_external.altea.vo.inv_advancedgetflightdatareply_15_2_1a;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApplicationErrorDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicationErrorDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="applicationErrorCode" type="{http://xml.amadeus.com/IFLIRR_15_2_1A}AlphaNumericString_Length1To5"/>
 *         &lt;element name="codeListQualifier" type="{http://xml.amadeus.com/IFLIRR_15_2_1A}AlphaNumericString_Length1To3"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationErrorDetailType", propOrder = {
    "applicationErrorCode",
    "codeListQualifier"
})
public class ApplicationErrorDetailType {

    @XmlElement(required = true)
    protected String applicationErrorCode;
    @XmlElement(required = true)
    protected String codeListQualifier;

    /**
     * Gets the value of the applicationErrorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationErrorCode() {
        return applicationErrorCode;
    }

    /**
     * Sets the value of the applicationErrorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationErrorCode(String value) {
        this.applicationErrorCode = value;
    }

    /**
     * Gets the value of the codeListQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeListQualifier() {
        return codeListQualifier;
    }

    /**
     * Sets the value of the codeListQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeListQualifier(String value) {
        this.codeListQualifier = value;
    }

}
