//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.11 at 03:15:49 ���� KST 
//


package com.koreanair.common_external.altea.vo.salesreports_displaytransactionreportreply_11_1_1a;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.koreanair.common_external.altea.vo.salesreports_displaytransactionreportreply_11_1_1a package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.koreanair.common_external.altea.vo.salesreports_displaytransactionreportreply_11_1_1a
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ItemNumberIdentificationTypeI }
     * 
     */
    public ItemNumberIdentificationTypeI createItemNumberIdentificationTypeI() {
        return new ItemNumberIdentificationTypeI();
    }

    /**
     * Create an instance of {@link PricingTicketingInformationTypeI }
     * 
     */
    public PricingTicketingInformationTypeI createPricingTicketingInformationTypeI() {
        return new PricingTicketingInformationTypeI();
    }

    /**
     * Create an instance of {@link TransactionInformationForTicketingType }
     * 
     */
    public TransactionInformationForTicketingType createTransactionInformationForTicketingType() {
        return new TransactionInformationForTicketingType();
    }

    /**
     * Create an instance of {@link TaxDetailsTypeI }
     * 
     */
    public TaxDetailsTypeI createTaxDetailsTypeI() {
        return new TaxDetailsTypeI();
    }

    /**
     * Create an instance of {@link ReservationControlInformationTypeI }
     * 
     */
    public ReservationControlInformationTypeI createReservationControlInformationTypeI() {
        return new ReservationControlInformationTypeI();
    }

    /**
     * Create an instance of {@link TravellerInformationTypeI }
     * 
     */
    public TravellerInformationTypeI createTravellerInformationTypeI() {
        return new TravellerInformationTypeI();
    }

    /**
     * Create an instance of {@link MonetaryInformationTypeI52231S }
     * 
     */
    public MonetaryInformationTypeI52231S createMonetaryInformationTypeI52231S() {
        return new MonetaryInformationTypeI52231S();
    }

    /**
     * Create an instance of {@link SelectionDetailsInformationTypeI }
     * 
     */
    public SelectionDetailsInformationTypeI createSelectionDetailsInformationTypeI() {
        return new SelectionDetailsInformationTypeI();
    }

    /**
     * Create an instance of {@link SelectionDetailsTypeI }
     * 
     */
    public SelectionDetailsTypeI createSelectionDetailsTypeI() {
        return new SelectionDetailsTypeI();
    }

    /**
     * Create an instance of {@link MonetaryInformationDetailsTypeI }
     * 
     */
    public MonetaryInformationDetailsTypeI createMonetaryInformationDetailsTypeI() {
        return new MonetaryInformationDetailsTypeI();
    }

    /**
     * Create an instance of {@link TourInformationTypeI }
     * 
     */
    public TourInformationTypeI createTourInformationTypeI() {
        return new TourInformationTypeI();
    }

    /**
     * Create an instance of {@link AdditionalBusinessSourceInformationTypeI }
     * 
     */
    public AdditionalBusinessSourceInformationTypeI createAdditionalBusinessSourceInformationTypeI() {
        return new AdditionalBusinessSourceInformationTypeI();
    }

    /**
     * Create an instance of {@link FreeTextDetailsType }
     * 
     */
    public FreeTextDetailsType createFreeTextDetailsType() {
        return new FreeTextDetailsType();
    }

    /**
     * Create an instance of {@link CouponInformationType }
     * 
     */
    public CouponInformationType createCouponInformationType() {
        return new CouponInformationType();
    }

    /**
     * Create an instance of {@link ErrorGroupType }
     * 
     */
    public ErrorGroupType createErrorGroupType() {
        return new ErrorGroupType();
    }

    /**
     * Create an instance of {@link SalesReportsDisplayTransactionReportReply }
     * 
     */
    public SalesReportsDisplayTransactionReportReply createSalesReportsDisplayTransactionReportReply() {
        return new SalesReportsDisplayTransactionReportReply();
    }

    /**
     * Create an instance of {@link SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails }
     * 
     */
    public SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails createSalesReportsDisplayTransactionReportReplyTransactionReportDataDetails() {
        return new SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails();
    }

    /**
     * Create an instance of {@link ReservationControlInformationDetailsTypeI }
     * 
     */
    public ReservationControlInformationDetailsTypeI createReservationControlInformationDetailsTypeI() {
        return new ReservationControlInformationDetailsTypeI();
    }

    /**
     * Create an instance of {@link CodedAttributeInformationType }
     * 
     */
    public CodedAttributeInformationType createCodedAttributeInformationType() {
        return new CodedAttributeInformationType();
    }

    /**
     * Create an instance of {@link TicketNumberDetailsTypeI84557C }
     * 
     */
    public TicketNumberDetailsTypeI84557C createTicketNumberDetailsTypeI84557C() {
        return new TicketNumberDetailsTypeI84557C();
    }

    /**
     * Create an instance of {@link FormOfPaymentTypeI }
     * 
     */
    public FormOfPaymentTypeI createFormOfPaymentTypeI() {
        return new FormOfPaymentTypeI();
    }

    /**
     * Create an instance of {@link CouponInformationDetailsType }
     * 
     */
    public CouponInformationDetailsType createCouponInformationDetailsType() {
        return new CouponInformationDetailsType();
    }

    /**
     * Create an instance of {@link ReferenceInfoType }
     * 
     */
    public ReferenceInfoType createReferenceInfoType() {
        return new ReferenceInfoType();
    }

    /**
     * Create an instance of {@link InternalIDDetailsType }
     * 
     */
    public InternalIDDetailsType createInternalIDDetailsType() {
        return new InternalIDDetailsType();
    }

    /**
     * Create an instance of {@link PricingTicketingDetailsTypeI }
     * 
     */
    public PricingTicketingDetailsTypeI createPricingTicketingDetailsTypeI() {
        return new PricingTicketingDetailsTypeI();
    }

    /**
     * Create an instance of {@link TicketNumberDetailsTypeI }
     * 
     */
    public TicketNumberDetailsTypeI createTicketNumberDetailsTypeI() {
        return new TicketNumberDetailsTypeI();
    }

    /**
     * Create an instance of {@link TicketNumberTypeI }
     * 
     */
    public TicketNumberTypeI createTicketNumberTypeI() {
        return new TicketNumberTypeI();
    }

    /**
     * Create an instance of {@link SpecificDataInformationTypeI }
     * 
     */
    public SpecificDataInformationTypeI createSpecificDataInformationTypeI() {
        return new SpecificDataInformationTypeI();
    }

    /**
     * Create an instance of {@link SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.FeeGroup }
     * 
     */
    public SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.FeeGroup createSalesReportsDisplayTransactionReportReplyTransactionReportDataDetailsFeeGroup() {
        return new SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.FeeGroup();
    }

    /**
     * Create an instance of {@link TransactionInformationsType }
     * 
     */
    public TransactionInformationsType createTransactionInformationsType() {
        return new TransactionInformationsType();
    }

    /**
     * Create an instance of {@link OriginatorIdentificationDetailsTypeI }
     * 
     */
    public OriginatorIdentificationDetailsTypeI createOriginatorIdentificationDetailsTypeI() {
        return new OriginatorIdentificationDetailsTypeI();
    }

    /**
     * Create an instance of {@link TicketAgentInfoType }
     * 
     */
    public TicketAgentInfoType createTicketAgentInfoType() {
        return new TicketAgentInfoType();
    }

    /**
     * Create an instance of {@link DocumentDetailsTypeI }
     * 
     */
    public DocumentDetailsTypeI createDocumentDetailsTypeI() {
        return new DocumentDetailsTypeI();
    }

    /**
     * Create an instance of {@link DocumentInformationDetailsTypeI }
     * 
     */
    public DocumentInformationDetailsTypeI createDocumentInformationDetailsTypeI() {
        return new DocumentInformationDetailsTypeI();
    }

    /**
     * Create an instance of {@link TourDetailsTypeI }
     * 
     */
    public TourDetailsTypeI createTourDetailsTypeI() {
        return new TourDetailsTypeI();
    }

    /**
     * Create an instance of {@link FreeTextInformationType }
     * 
     */
    public FreeTextInformationType createFreeTextInformationType() {
        return new FreeTextInformationType();
    }

    /**
     * Create an instance of {@link CodedAttributeType }
     * 
     */
    public CodedAttributeType createCodedAttributeType() {
        return new CodedAttributeType();
    }

    /**
     * Create an instance of {@link FOPRepresentationType }
     * 
     */
    public FOPRepresentationType createFOPRepresentationType() {
        return new FOPRepresentationType();
    }

    /**
     * Create an instance of {@link MonetaryInformationTypeI }
     * 
     */
    public MonetaryInformationTypeI createMonetaryInformationTypeI() {
        return new MonetaryInformationTypeI();
    }

    /**
     * Create an instance of {@link SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.ExchangedGroup }
     * 
     */
    public SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.ExchangedGroup createSalesReportsDisplayTransactionReportReplyTransactionReportDataDetailsExchangedGroup() {
        return new SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.ExchangedGroup();
    }

    /**
     * Create an instance of {@link StructuredDateTimeInformationType }
     * 
     */
    public StructuredDateTimeInformationType createStructuredDateTimeInformationType() {
        return new StructuredDateTimeInformationType();
    }

    /**
     * Create an instance of {@link ReferencingDetailsTypeI }
     * 
     */
    public ReferencingDetailsTypeI createReferencingDetailsTypeI() {
        return new ReferencingDetailsTypeI();
    }

    /**
     * Create an instance of {@link FormOfPaymentDetailsTypeI }
     * 
     */
    public FormOfPaymentDetailsTypeI createFormOfPaymentDetailsTypeI() {
        return new FormOfPaymentDetailsTypeI();
    }

    /**
     * Create an instance of {@link SourceTypeDetailsTypeI }
     * 
     */
    public SourceTypeDetailsTypeI createSourceTypeDetailsTypeI() {
        return new SourceTypeDetailsTypeI();
    }

    /**
     * Create an instance of {@link TravellerSurnameInformationTypeI }
     * 
     */
    public TravellerSurnameInformationTypeI createTravellerSurnameInformationTypeI() {
        return new TravellerSurnameInformationTypeI();
    }

    /**
     * Create an instance of {@link TicketNumberTypeI63924S }
     * 
     */
    public TicketNumberTypeI63924S createTicketNumberTypeI63924S() {
        return new TicketNumberTypeI63924S();
    }

    /**
     * Create an instance of {@link StructuredDateTimeType }
     * 
     */
    public StructuredDateTimeType createStructuredDateTimeType() {
        return new StructuredDateTimeType();
    }

    /**
     * Create an instance of {@link ItemNumberTypeI }
     * 
     */
    public ItemNumberTypeI createItemNumberTypeI() {
        return new ItemNumberTypeI();
    }

    /**
     * Create an instance of {@link DataTypeInformationTypeI }
     * 
     */
    public DataTypeInformationTypeI createDataTypeInformationTypeI() {
        return new DataTypeInformationTypeI();
    }

    /**
     * Create an instance of {@link SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.FeeGroup.FeeDetails }
     * 
     */
    public SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.FeeGroup.FeeDetails createSalesReportsDisplayTransactionReportReplyTransactionReportDataDetailsFeeGroupFeeDetails() {
        return new SalesReportsDisplayTransactionReportReply.TransactionReportDataDetails.FeeGroup.FeeDetails();
    }

    /**
     * Create an instance of {@link ApplicationErrorDetailType }
     * 
     */
    public ApplicationErrorDetailType createApplicationErrorDetailType() {
        return new ApplicationErrorDetailType();
    }

    /**
     * Create an instance of {@link MonetaryInformationDetailsTypeI85122C }
     * 
     */
    public MonetaryInformationDetailsTypeI85122C createMonetaryInformationDetailsTypeI85122C() {
        return new MonetaryInformationDetailsTypeI85122C();
    }

    /**
     * Create an instance of {@link TaxTypeI }
     * 
     */
    public TaxTypeI createTaxTypeI() {
        return new TaxTypeI();
    }

    /**
     * Create an instance of {@link ApplicationErrorInformationType }
     * 
     */
    public ApplicationErrorInformationType createApplicationErrorInformationType() {
        return new ApplicationErrorInformationType();
    }

}
