//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 06:12:58 ���� KST 
//


package com.koreanair.common_external.altea.vo.service_priceserviceviacataloguereply_12_3_1a;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Created by importexport 02/10/2002 16:43
 * 
 * <p>Java class for FareCalcConstructionInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FareCalcConstructionInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fareCalculationCodeDetails" type="{http://xml.amadeus.com/TPSCGR_12_3_1A}FareCalculationCodeDetailsType"/>
 *         &lt;element name="monetaryInfo" type="{http://xml.amadeus.com/TPSCGR_12_3_1A}MonetaryInformationType_67627S" minOccurs="0"/>
 *         &lt;element name="upFareDetails" type="{http://xml.amadeus.com/TPSCGR_12_3_1A}FareQualifierDetailsType" minOccurs="0"/>
 *         &lt;element name="cumulatedChargesInfo" type="{http://xml.amadeus.com/TPSCGR_12_3_1A}NumberOfUnitsType_67575S" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FareCalcConstructionInfoType", propOrder = {
    "fareCalculationCodeDetails",
    "monetaryInfo",
    "upFareDetails",
    "cumulatedChargesInfo"
})
public class FareCalcConstructionInfoType {

    @XmlElement(required = true)
    protected FareCalculationCodeDetailsType fareCalculationCodeDetails;
    protected MonetaryInformationType67627S monetaryInfo;
    protected FareQualifierDetailsType upFareDetails;
    protected NumberOfUnitsType67575S cumulatedChargesInfo;

    /**
     * Gets the value of the fareCalculationCodeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link FareCalculationCodeDetailsType }
     *     
     */
    public FareCalculationCodeDetailsType getFareCalculationCodeDetails() {
        return fareCalculationCodeDetails;
    }

    /**
     * Sets the value of the fareCalculationCodeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link FareCalculationCodeDetailsType }
     *     
     */
    public void setFareCalculationCodeDetails(FareCalculationCodeDetailsType value) {
        this.fareCalculationCodeDetails = value;
    }

    /**
     * Gets the value of the monetaryInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryInformationType67627S }
     *     
     */
    public MonetaryInformationType67627S getMonetaryInfo() {
        return monetaryInfo;
    }

    /**
     * Sets the value of the monetaryInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryInformationType67627S }
     *     
     */
    public void setMonetaryInfo(MonetaryInformationType67627S value) {
        this.monetaryInfo = value;
    }

    /**
     * Gets the value of the upFareDetails property.
     * 
     * @return
     *     possible object is
     *     {@link FareQualifierDetailsType }
     *     
     */
    public FareQualifierDetailsType getUpFareDetails() {
        return upFareDetails;
    }

    /**
     * Sets the value of the upFareDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link FareQualifierDetailsType }
     *     
     */
    public void setUpFareDetails(FareQualifierDetailsType value) {
        this.upFareDetails = value;
    }

    /**
     * Gets the value of the cumulatedChargesInfo property.
     * 
     * @return
     *     possible object is
     *     {@link NumberOfUnitsType67575S }
     *     
     */
    public NumberOfUnitsType67575S getCumulatedChargesInfo() {
        return cumulatedChargesInfo;
    }

    /**
     * Sets the value of the cumulatedChargesInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberOfUnitsType67575S }
     *     
     */
    public void setCumulatedChargesInfo(NumberOfUnitsType67575S value) {
        this.cumulatedChargesInfo = value;
    }

}
